#!/usr/bin/env python

"""Generate SimXOrder.json, the constant NtwtfDecode needs to rebuild SimX strings.

Every save's Variable table carries a Conversation_SimX_<articy id> entry per
conversation, holding "<dialogue articy id>;<status code>;..." for every dialogue
entry of that conversation. The statuses are the same data the Conversation
table's Dialog maps already hold, so the sparse form leaves the whole block out
and rebuilds it - but only the statuses are derivable. The order the dialogue ids
come in is the game's own Lua table order: constant for a build, and in no order
this repo can compute.

So that order is recorded here, once, as the moves that turn the sequence implied
by articy_ids_final_cut.json into the one the save actually holds. Written as
moves rather than as the ids themselves because it is about a tenth of the size.

Run this when the articy id map changes, from the repository root:

    python tools/NtwtfDecode/generate_simx_order.py testing/save_template.ntwtf.zip
"""

import argparse
import bisect
import json
import subprocess
import sys
import tempfile
import traceback

from collections import defaultdict
from pathlib import Path

ARTICY_IDS = "articy_ids_final_cut.json"
OUTPUT = Path("tools") / "NtwtfDecode" / "SimXOrder.json"
SIMX_PREFIX = "Conversation_SimX_"

###############################################################################
# Core functions
###############################################################################


def split_save(repo, save, out_dir):
    subprocess.run(
        [
            "dotnet",
            "run",
            "--project",
            str(repo / "tools" / "NtwtfDecode"),
            "--",
            str(save),
            "--split",
            "-o",
            str(out_dir),
        ],
        check=True,
        cwd=repo,
        stdout=subprocess.DEVNULL,
    )


def canonical_sequences(articy_map):
    """Per conversation index, its (dialogue index, articy id) pairs, sorted."""
    sequences = defaultdict(list)
    for articy_id, (conversation, indices) in articy_map["dialogue_entries"].items():
        for index in indices:
            sequences[conversation].append((index, articy_id))
    for pairs in sequences.values():
        pairs.sort()
    return sequences


def moves(canonical, observed):
    """The fewest lift-and-reinsert moves, matching SparseOrder.Moves in C#."""
    slots = defaultdict(list)
    for i, item in enumerate(canonical):
        slots[item].append(i)
    taken = defaultdict(int)
    where = []
    for item in observed:
        where.append(slots[item][taken[item]])
        taken[item] += 1

    tails, previous = [], [-1] * len(where)
    for i, value in enumerate(where):
        at = bisect.bisect_left([where[t] for t in tails], value)
        previous[i] = tails[at - 1] if at else -1
        if at == len(tails):
            tails.append(i)
        else:
            tails[at] = i
    keep, i = set(), tails[-1] if tails else -1
    while i >= 0:
        keep.add(i)
        i = previous[i]
    return [(where[i], i) for i in range(len(where)) if i not in keep]


def pack_moves(pairs):
    return ",".join(f"{a}:{b}" for a, b in pairs)


def generate(repo, save):
    articy_map = json.loads((repo / ARTICY_IDS).read_text(encoding="utf-8"))
    conversations = articy_map["conversations"]
    sequences = canonical_sequences(articy_map)

    with tempfile.TemporaryDirectory() as work:
        parts = Path(work) / "parts"
        split_save(repo, save, parts)
        variables = json.loads((parts / "Variable.json").read_text(encoding="utf-8"))

    orders, skipped = {}, []
    for name, value in variables.items():
        if not name.startswith(SIMX_PREFIX):
            continue
        owner = name[len(SIMX_PREFIX) :]
        index = conversations.get(owner)
        if index is None:
            skipped.append(owner)
            continue
        observed = value.split(";")[0::2]
        canonical = [articy_id for _, articy_id in sequences[index]]
        if sorted(canonical) != sorted(observed):
            skipped.append(owner)
            continue
        pairs = moves(canonical, observed)
        if pairs:
            orders[str(index)] = pack_moves(pairs)

    document = {
        "_comment": (
            "Generated by tools/NtwtfDecode/generate_simx_order.py. Moves that turn "
            "the dialogue id sequence implied by "
            + ARTICY_IDS
            + " into the order a "
            "save's Conversation_SimX_* strings use. Keyed by conversation index; a "
            "conversation whose order already matches is absent."
        ),
        "articy_ids": ARTICY_IDS,
        "orders": dict(sorted(orders.items(), key=lambda kv: int(kv[0]))),
    }
    out = repo / OUTPUT
    out.write_text(json.dumps(document, indent=1, sort_keys=False) + "\n", encoding="utf-8")
    total = sum(len(v.split(",")) for v in orders.values())
    print(f"wrote {out} ({out.stat().st_size:,} bytes)")
    print(f"  {len(orders):,} conversations need moves, {total:,} moves in all")
    if skipped:
        print(f"  {len(skipped)} conversation(s) could not be matched and will stay literal")


###############################################################################
# CLI
###############################################################################


def get_parser():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("save", help="A save to read the dialogue id order from")
    parser.add_argument("--repo", default=".", help="Repository root")
    return parser


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]
    args = get_parser().parse_args(argv)
    try:
        generate(Path(args.repo).resolve(), Path(args.save).resolve())
    except Exception:  # pylint: disable=broad-except
        traceback.print_exc()
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
