// SPDX-License-Identifier: MIT
using System.Globalization;
using System.Reflection;
using System.Text.Json;

namespace NtwtfDecode;

/// <summary>
/// The constant order in which a conversation's dialogue entries appear inside a
/// <c>Conversation_SimX_*</c> variable.
/// </summary>
/// <remarks>
/// <para>
/// The statuses in those strings are the same data the Conversation table's Dialog
/// maps hold, so the sparse form leaves the strings out and rebuilds them. What it
/// cannot compute is the order the dialogue ids come in: that is the game's own Lua
/// table order, which is fixed for a build but in no order this repo can derive.
/// </para>
/// <para>
/// So the order is recorded once. <c>articy_ids_final_cut.json</c>, which the repo
/// already carries, says which dialogue entries belong to a conversation;
/// <c>SimXOrder.json</c>, generated by <c>generate_simx_order.py</c>, says how to
/// rearrange them. Everything here is a claim about constant game data, and every
/// use of it is checked against the save being converted, so a stale constant makes
/// the output bigger and never makes it wrong.
/// </para>
/// </remarks>
public sealed class SimXOrders
{
    /// <summary>The id map this repo carries, and which the order manifest is against.</summary>
    public const string ArticyIdsFileName = "articy_ids_final_cut.json";

    /// <summary>The generated manifest, embedded in this assembly.</summary>
    public const string OrderResourceName = "SimXOrder.json";

    private readonly Dictionary<int, List<(string ArticyId, int DialogueIndex)>> _sequences;
    private readonly Dictionary<string, int> _conversationIndex;

    private SimXOrders(
        Dictionary<int, List<(string, int)>> sequences,
        Dictionary<string, int> conversationIndex
    )
    {
        _sequences = sequences;
        _conversationIndex = conversationIndex;
    }

    /// <summary>
    /// Loads the constants, or returns null when the articy id map is not beside the
    /// repository. Sparse conversion then leaves the SimX strings alone rather than
    /// failing, which keeps the tool usable outside a checkout.
    /// </summary>
    public static SimXOrders? TryLoad()
    {
        string? articyPath = FindRepositoryFile(ArticyIdsFileName);
        if (articyPath is null)
        {
            return null;
        }

        using FileStream articyStream = File.OpenRead(articyPath);
        using JsonDocument articy = JsonDocument.Parse(articyStream);
        var conversationIndex = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (JsonProperty entry in articy.RootElement.GetProperty("conversations").EnumerateObject())
        {
            conversationIndex[entry.Name] = entry.Value.GetInt32();
        }

        var sequences = new Dictionary<int, List<(string, int)>>();
        foreach (
            JsonProperty entry in articy.RootElement.GetProperty("dialogue_entries").EnumerateObject()
        )
        {
            int conversation = entry.Value[0].GetInt32();
            if (!sequences.TryGetValue(conversation, out List<(string, int)>? pairs))
            {
                pairs = new List<(string, int)>();
                sequences[conversation] = pairs;
            }
            foreach (JsonElement index in entry.Value[1].EnumerateArray())
            {
                pairs.Add((entry.Name, index.GetInt32()));
            }
        }
        foreach (List<(string ArticyId, int DialogueIndex)> pairs in sequences.Values)
        {
            // The canonical order the manifest's moves are against.
            pairs.Sort(
                (a, b) =>
                    a.DialogueIndex != b.DialogueIndex
                        ? a.DialogueIndex.CompareTo(b.DialogueIndex)
                        : string.CompareOrdinal(a.ArticyId, b.ArticyId)
            );
        }

        ApplyRecordedMoves(sequences);
        return new SimXOrders(sequences, conversationIndex);
    }

    /// <summary>The conversation index an articy id names, or null when unknown.</summary>
    public int? ConversationIndex(string articyId) =>
        _conversationIndex.TryGetValue(articyId, out int index) ? index : null;

    /// <summary>
    /// The dialogue entries of a conversation, in the order its SimX string lists
    /// them, or null when the conversation is not in the map.
    /// </summary>
    public IReadOnlyList<(string ArticyId, int DialogueIndex)>? SequenceFor(int conversation) =>
        _sequences.TryGetValue(conversation, out List<(string, int)>? pairs) ? pairs : null;

    private static void ApplyRecordedMoves(Dictionary<int, List<(string, int)>> sequences)
    {
        using Stream? resource = typeof(SimXOrders).Assembly.GetManifestResourceStream(
            typeof(SimXOrders).Namespace + "." + OrderResourceName
        );
        if (resource is null)
        {
            throw new InvalidDataException(
                $"{OrderResourceName} is missing from the {nameof(NtwtfDecode)} assembly"
            );
        }

        using JsonDocument document = JsonDocument.Parse(resource);
        foreach (JsonProperty entry in document.RootElement.GetProperty("orders").EnumerateObject())
        {
            int conversation = int.Parse(entry.Name, CultureInfo.InvariantCulture);
            if (!sequences.TryGetValue(conversation, out List<(string, int)>? pairs))
            {
                continue;
            }
            sequences[conversation] = SparseOrder.ApplyMoves(
                pairs,
                SparseOrder.UnpackMoves(entry.Value.GetString(), OrderResourceName)
            );
        }
    }

    /// <summary>
    /// Looks for a repository file beside the running assembly and beside the
    /// working directory, walking up from each.
    /// </summary>
    private static string? FindRepositoryFile(string name)
    {
        foreach (string start in new[] { AppContext.BaseDirectory, Directory.GetCurrentDirectory() })
        {
            for (
                DirectoryInfo? directory = new(start);
                directory is not null;
                directory = directory.Parent
            )
            {
                string candidate = Path.Combine(directory.FullName, name);
                if (File.Exists(candidate))
                {
                    return candidate;
                }
            }
        }
        return null;
    }
}
