

AreaState["CHURCH_AUXWIRE"]={LocationState=0};
AreaState["CHURCH_DRUGLAB"]={LocationState=0};
AreaState["CHURCH_MAINFRAME"]={LocationState=0};
AreaState["CHURCH_PLATES"]={LocationState=0};
AreaState["CHURCH_RAVERS"]={LocationState=0};
AreaState["CHURCH_SOONA"]={LocationState=0};
AreaState["CHURCH_TIAGO"]={LocationState=0};
AreaState["CHURCH_PROTORAVE"]={LocationState=0};
AreaState["CHURCH_LIGHTS"]={LocationState=0};
AreaState["CHURCH_RUMBLING"]={LocationState=0};
AreaState["DOOMED_CURTAINS"]={LocationState=0};
AreaState["DOOMED_DOOR"]={LocationState=0};
AreaState["DOOMED_FRIDGE"]={LocationState=0};
AreaState["DOOMED_RADIOCOMPUTER"]={LocationState=0};
AreaState["DOOMED_ICECREAM"]={LocationState=0};
AreaState["POWER_PLUG_RED"]={LocationState=0};
AreaState["POWER_PLUG_BLACK"]={LocationState=0};
AreaState["FISHING_BOAT"]={LocationState=0};
AreaState["SEA_MODE"]={LocationState=0};
AreaState["FORTRESS_DESERTERGUN"]={LocationState=0};
AreaState["FORTRESS_BLAST_DOOR"]={LocationState=0};
AreaState["FORTRESS_GENERATOR"]={LocationState=0};
AreaState["FORTRESS_PHASMID"]={LocationState=0};
AreaState["FORTRESS_PHASMID_ANIM"]={LocationState=0};
AreaState["GATES_MEASUREHEAD"]={LocationState=0};
AreaState["GATES_MANANA"]={LocationState=1};
AreaState["HANGED_MAN"]={LocationState=0};
AreaState["HANGED_MAN_BOOTS"]={LocationState=0};
AreaState["HANGED_MAN_BRANCH"]={LocationState=0};
AreaState["YARD_ETERNITE"]={LocationState=0};
AreaState["WALL_GRAFFITO"]={LocationState=0};
AreaState["KLAASJE"]={LocationState=0};
AreaState["WHIRLING_CAFE_DOOR"]={LocationState=0};
AreaState["WHIRLING_PINBALL"]={LocationState=1};
AreaState["WHIRLING_TEQUILA_BEDROOM"]={LocationState=0};
AreaState["WHIRLING_GARDENER"]={LocationState=0};
AreaState["INSTIGATOR_STEEL_DOOR"]={LocationState=0};
AreaState["INSTIGATOR_RUBY"]={LocationState=0};
AreaState["INSTIGATOR_COMPRESSOR"]={LocationState=0};
AreaState["INSTIGATOR_COMPRESSOR_BUZZ"]={LocationState=0};
AreaState["INSTIGATOR_FOW"]={LocationState=0};
AreaState["TRIBUNAL"]={LocationState=0};
AreaState["BOARDWALK_PIGS"]={LocationState=0};
AreaState["BOARDWALK_PIGS_TRIGGER"]={LocationState=0};
AreaState["BOARDWALK_PIGS_LIGHTS"]={LocationState=0};
AreaState["HARBOUR_CLOAK"]={LocationState=0};
AreaState["HARBOUR_CONTAINER"]={LocationState=0};
AreaState["JOYCE"]={LocationState=0};
AreaState["PLAZA_DUDES"]={LocationState=0};
AreaState["PLAZA_GASTON"]={LocationState=0};
AreaState["SUNKEN_CAR"]={LocationState=0};
AreaState["WATERLOCK_GATE"]={LocationState=1};
AreaState["ICE_ETERNITE"]={LocationState=1};
AreaState["CANAL_HAWTHORN"]={LocationState=0};
AreaState["KINEEMA_LIGHTS"]={LocationState=0};
AreaState["CRYPTOFASCIST_CUIRASS"]={LocationState=0};
AreaState["PETANQUE_CUTSCENE"]={LocationState=0};
AreaState["FUEL_IS_BURNING"]={LocationState=0};
AreaState["ANTENNA_VISIBLE"]={LocationState=0};
AreaState["SOONA_MONUMENT_POS"]={LocationState=0};
AreaState["NOID_MONUMENT_POS"]={LocationState=0};
AreaState["MATCHBOXTOWER"]={LocationState=0};
AreaState["MATCHBOXTOWER_LOC"]={LocationState=0};
AreaState["TRANSCEIVER_TYPE"]={LocationState=0};
AreaState["POSSE_LOC"]={LocationState=0};
AreaState["PARTY_ISLAND"]={LocationState=0};
AreaState["AIRSHIP"]={LocationState=0};
AreaState["MONUMENT_SWORD"]={LocationState=0};
AreaState["MEASUREHEAD_COACH"]={LocationState=0};
AreaState["HIDE_TRANT"]={LocationState=0};
AreaState["HIDE_MHEAD"]={LocationState=0};
AreaState["ITEM_HELD"]={LocationState=0};
AreaState["URR_SPAWN"]={LocationState=0};
AreaState["ART_COP"]={LocationState=0};
AreaState["ANTENNA_PROPS"]={LocationState=0};
AreaState["MONUMENT_BENT"]={LocationState=0};
AreaState["MONUMENT_HEAD_STATE"]={LocationState=0};
AreaState["AIRSHIP_SHADOW"]={LocationState=0};
AreaState["PAWNSHOP_SIGN"]={LocationState=0};
AreaState["SEAGULL_LANDMARK"]={LocationState=0};
AreaState["KIM_PF_JACKET"]={LocationState=0};
AreaState["SEAGULL_WINGS"]={LocationState=0};
AreaState["PINBALL_LIGHTS"]={LocationState=0};
AreaState["PINBALL_SOUND"]={LocationState=0};
AreaState["PINBALL_FOG"]={LocationState=0};
AreaState["PINBALL_POS"]={LocationState=0};
AreaState["PLEASUREWHEEL"]={LocationState=0};
AreaState["AUTHORITY_LIGHTS"]={LocationState=0};
AreaState["LEDGER"]={LocationState=0};
AreaState["Init"]={HasEntered=false};
AreaState["Church-int"]={HasEntered=false};
AreaState["Character Select Screen"]={HasEntered=false};
AreaState["Block-in Playground"]={HasEntered=false};
AreaState["Whirling-int-f1"]={HasEntered=false};
AreaState["Whirling-int-f2"]={HasEntered=false};
AreaState["Martinaise-ext"]={HasEntered=false};
AreaState["sense-of-scale"]={HasEntered=false};
AreaState["Doomed-commerce-int-f2"]={HasEntered=false};
AreaState["Doomed-commerce-int-f1"]={HasEntered=false};
AreaState["Doomed-commerce-int-s1"]={HasEntered=false};
AreaState["Kiosque-int"]={HasEntered=false};
AreaState["Capeside-apartments-int"]={HasEntered=false};
AreaState["Whirling-int-f3"]={HasEntered=false};
AreaState["Capeside-coalchamber-int"]={HasEntered=false};
AreaState["Secretary-int"]={HasEntered=false};
AreaState["Pawnshop-int"]={HasEntered=false};
AreaState["Cunos-shack-int"]={HasEntered=false};
AreaState["Capeside-smoker-int"]={HasEntered=false};
AreaState["Sea-fortress-int"]={HasEntered=false};
AreaState["Tent-int"]={HasEntered=false};
AreaState["Second-home-int"]={HasEntered=false};
AreaState["FV-house-int"]={HasEntered=false};
AreaState["Instigators-lair-int"]={HasEntered=false};
AreaState["Union-container-int"]={HasEntered=false};
AreaState["Union-boss-int"]={HasEntered=false};
AreaState["Capeside-wcw-int"]={HasEntered=false};
AreaState["Crypto-garys-apt-int"]={HasEntered=false};
AreaState["Dream-2"]={HasEntered=false};
AreaState["FV-shack-int"]={HasEntered=false};
AreaState["Feld-int"]={HasEntered=false};
AreaState["Dream-3-ext"]={HasEntered=false};
AreaState["Dream-3-int"]={HasEntered=false};
AreaState["Whirling-int-f3-antechamber"]={HasEntered=false};
AreaState["Commustudent-int"]={HasEntered=false};
AreaState["InitOS"]={HasEntered=false};
AreaState["collageMode"]={HasEntered=false};
AreaState["Scenes/Whirling-int-f2"]={HasEntered=true};
AreaState["Shoe snakeskin left"]={disappear=true};
AreaState["Boot-cut pants"]={disappear=true};
AreaState["tequila_tie_hanging"]={disappear=true};
AreaState["Disco-ass blazer"]={disappear=true};
AreaState["Dress Shirt Hanging"]={disappear=true};
AreaState["Whirling table money"]={disappear=true};
AreaState["Scenes/Martinaise-ext"]={HasEntered=true};
AreaState["Shoe snakeskin right"]={disappear=true};
AreaState["Klaasje"]={disappear=true};
AreaState["Scenes/Whirling-int-f1"]={HasEntered=true};
AreaState["Cutlery"]={emptied=true};
AreaState["Car Crate"]={emptied=true};
AreaState["Jam Crates left"]={emptied=true};
AreaState["Jam Money 2"]={disappear=true};
AreaState["Jam Money"]={disappear=true};
AreaState["Fritte Trashcan"]={emptied=true};
AreaState["Scenes/Kiosque-int"]={HasEntered=true};
AreaState["plastic_bag_container(Clone)"]={disappear=true};
AreaState["box pawnshop"]={disappear=true};
AreaState["Waterlock Dumpster"]={emptied=true};
AreaState["Scenes/Pawnshop-int"]={HasEntered=true};
AreaState["Scenes/Doomed-commerce-int-f1"]={HasEntered=true};
AreaState["Yard Woodpile"]={emptied=true};
AreaState["Yard Crate"]={emptied=true};
AreaState["Pier Bagpile"]={emptied=true};
AreaState["Yard Box 2"]={emptied=true};
AreaState["Box"]={emptied=true};
AreaState["Scenes/Dream-2"]={HasEntered=true};
AreaState["Doomed Trash Can"]={emptied=true};
AreaState["empty bottle"]={disappear=true};
AreaState["can"]={disappear=true};
AreaState["Pier Trash Can"]={emptied=true};
AreaState["Pier Trash Can 2"]={emptied=true};
AreaState["Waterlock Trash Can"]={emptied=true};
AreaState["crate_2 pawnshop"]={emptied=true};
AreaState["Pier Bag"]={emptied=true};
AreaState["Pier Bag 2"]={emptied=true};
AreaState["empty_beer"]={disappear=true};
AreaState["empty_beer (15)"]={disappear=true};
AreaState["empty_beer (3)"]={disappear=true};
AreaState["empty_beer (6)"]={disappear=true};
AreaState["Pier Dumpster"]={emptied=true};
AreaState["Scenes/Capeside-apartments-int"]={HasEntered=true};
AreaState["clickable_apps-fridge"]={emptied=true};
AreaState["Pier Crate "]={disappear=true};
AreaState["Box_Tare pier"]={emptied=true};
AreaState["Scenes/Capeside-coalchamber-int"]={HasEntered=true};
AreaState["Coal Door"]={emptied=true};
AreaState["Coal Grate"]={emptied=true};
AreaState["Box_1 pier"]={emptied=true};
AreaState["clickable_apps-box-2"]={emptied=true};
AreaState["clickable_apps-mailbox-2"]={emptied=true};
AreaState["clickable_apps-bin"]={emptied=true};
AreaState["clickable_apps-plate"]={emptied=true};
AreaState["Apartments Closet"]={emptied=true};
AreaState["FV money Canal"]={disappear=true};
AreaState["Waterlock Bricks"]={emptied=true};
AreaState["Waterlock Metalbox"]={emptied=true};
AreaState["Waterlock Moneybox"]={emptied=true};
AreaState["FV money Shack"]={disappear=true};
AreaState["Waterlock Tare"]={emptied=true};
AreaState["Village Junk"]={emptied=true};
AreaState["box_3 fv"]={emptied=true};
AreaState["Scenes/FV-shack-int"]={HasEntered=true};
AreaState["Shack Postcard"]={emptied=true};
AreaState["Shack Box"]={emptied=true};
AreaState["Village Barrel"]={emptied=true};
AreaState["box_4 fv unbuilt house"]={emptied=true};
AreaState["Crate Ruins"]={emptied=true};
AreaState["Village Woodpile"]={emptied=true};
AreaState["FV money (1)"]={disappear=true};
AreaState["crate_1 fv dock"]={emptied=true};
AreaState["Village Crate "]={emptied=true};
AreaState["Village Blue Barrel"]={emptied=true};
AreaState["Scenes/FV-house-int"]={HasEntered=true};
AreaState["Taxidermy Grouse"]={disappear=true};
AreaState["FV money (3)"]={disappear=true};
AreaState["FV money (4)"]={disappear=true};
AreaState["Canister"]={disappear=true};
AreaState["Boardwalk Rocks Crate"]={emptied=true};
AreaState["Boardwalk Woodpile"]={emptied=true};
AreaState["box_3 feld building"]={emptied=true};
AreaState["Abandoned Building Money"]={disappear=true};
AreaState["box_1 broadwalk"]={emptied=true};
AreaState["Morell Money"]={emptied=true};
AreaState["Boardwalk Feld Box"]={emptied=true};
AreaState["Boardwalk Vent R"]={emptied=true};
AreaState["Boardwalk Vent L"]={emptied=true};
AreaState["Fishmarket Barrels"]={emptied=true};
AreaState["Broadwalk Money Table"]={disappear=true};
AreaState["Fishmarket Machine"]={emptied=true};
AreaState["Fishmarket Crate"]={emptied=true};
AreaState["Fishmarket Woodpile 2"]={emptied=true};
AreaState["Filthy-jacket"]={disappear=true};
ShownOrbs["WHIRLING F2 ORB / locked door"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / commodore red"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / piles of tape"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / trashed tape player"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / bath"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / MONEY"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / sea smell"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / calendar"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / ashtray"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / trompe le monde"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / trompe le monde afterthought"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / karaoke mic"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / lyrics stand"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / speaker"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / summerdoor"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / menu"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / water cooler"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / kitchen door"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / mess hall door"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / broken pinball"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / spilled rum"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / wheelbarrow"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / streetsign fuck the police"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / streetsign pigs go home"]={OrbSeen=1};
ShownOrbs["JAM ORB / cargohold"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / whirling number"]={OrbSeen=1};
ShownOrbs["JAM ORB / humanox"]={OrbSeen=1};
ShownOrbs["JAM ORB / detritus"]={OrbSeen=1};
ShownOrbs["JAM ORB / foreigncar"]={OrbSeen=1};
ShownOrbs["GATES ORB / cannister"]={OrbSeen=1};
ShownOrbs["GATES ORB / portlogo"]={OrbSeen=1};
ShownOrbs["JAM ORB / frittestore"]={OrbSeen=1};
ShownOrbs["JAM ORB / newmagazine"]={OrbSeen=1};
ShownOrbs["JAM ORB / tendetectives"]={OrbSeen=1};
ShownOrbs["WHIRLING F2 ORB / kim in your room"]={OrbSeen=1};
ShownOrbs["GATES ORB / electroentrance"]={OrbSeen=1};
ShownOrbs["GATES ORB / noticesign"]={OrbSeen=1};
ShownOrbs["FRITTE ORB / windowflowers"]={OrbSeen=1};
ShownOrbs["FRITTE ORB / radio plays"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / crack"]={OrbSeen=1};
ShownOrbs["JAM ORB / fountain"]={OrbSeen=1};
ShownOrbs["JAM ORB / tiretrackstoroof"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / coin-operated viewer III"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / book wholeness"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / book erotica"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / book pate"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / book unimportant"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / book boring"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / future book"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / trashtutorialone"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / doomed number"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / sign to roundabout"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / sign to apts"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / newspaperongrate"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / trashtutorialtwo"]={OrbSeen=1};
ShownOrbs["PLAZA ORB / stone spheres"]={OrbSeen=1};
ShownOrbs["JAM ORB / drawbridge"]={OrbSeen=1};
ShownOrbs["JAM ORB / sewergrate"]={OrbSeen=1};
ShownOrbs["CANAL ORB / pawnshop sign"]={OrbSeen=1};
ShownOrbs["CANAL ORB / waterlock sign"]={OrbSeen=1};
ShownOrbs["JAM ORB / buttersigndown"]={OrbSeen=1};
ShownOrbs["PAWNSHOP ORB / cashregister"]={OrbSeen=1};
ShownOrbs["PAWNSHOP ORB / grimwoman"]={OrbSeen=1};
ShownOrbs["PAWNSHOP ORB / projector"]={OrbSeen=1};
ShownOrbs["PAWNSHOP ORB / back room clothes rack"]={OrbSeen=1};
ShownOrbs["BOOKSTORE ORB / hairdrier"]={OrbSeen=1};
ShownOrbs["BOOKSTORE ORB / millionart"]={OrbSeen=1};
ShownOrbs["BOOKSTORE ORB / windoworb"]={OrbSeen=1};
ShownOrbs["BOOKSTORE ORB / sports mags"]={OrbSeen=1};
ShownOrbs["BOOKSTORE ORB / stufforb"]={OrbSeen=1};
ShownOrbs["BOOKSTORE ORB / greatideas"]={OrbSeen=1};
ShownOrbs["BOOKSTORE ORB / shelforb"]={OrbSeen=1};
ShownOrbs["BOOKSTORE ORB / balconyorb"]={OrbSeen=1};
ShownOrbs["PIER ORB / cormoran"]={OrbSeen=1};
ShownOrbs["BACKYARD ORB / gardenhose"]={OrbSeen=1};
ShownOrbs["BACKYARD ORB / emptyarch"]={OrbSeen=1};
ShownOrbs["YARD ORB / door earlier"]={OrbSeen=1};
ShownOrbs["BACKYARD ORB / water barrels"]={OrbSeen=1};
ShownOrbs["BACKYARD ORB / balcony"]={OrbSeen=1};
ShownOrbs["PIER ORB / yellow boat"]={OrbSeen=1};
ShownOrbs["PIER ORB / street sign south"]={OrbSeen=1};
ShownOrbs["PIER ORB / street sign north"]={OrbSeen=1};
ShownOrbs["PIER ORB / insideofagarage"]={OrbSeen=1};
ShownOrbs["PIER ORB / paint origin"]={OrbSeen=1};
ShownOrbs["PIER ORB / post in water"]={OrbSeen=1};
ShownOrbs["PIER ORB / plaque"]={OrbSeen=1};
ShownOrbs["PIER ORB / steeringwheel"]={OrbSeen=1};
ShownOrbs["YARD ORB / winch"]={OrbSeen=1};
ShownOrbs["YARD ORB / greenhouse"]={OrbSeen=1};
ShownOrbs["BACKYARD ORB / witness logic"]={OrbSeen=1};
ShownOrbs["YARD ORB / trash container logo"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / undonedishes"]={OrbSeen=1};
ShownOrbs["YARD ORB / tree ladder"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 ORB / spitbowl"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 / hardie window clicked"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 / union box wall"]={OrbSeen=1};
ShownOrbs["WHIRLING F1 / cuttingboard"]={OrbSeen=1};
ShownOrbs["APT ORB / killtherich"]={OrbSeen=1};
ShownOrbs["APT ORB / foreclosed apt door"]={OrbSeen=1};
ShownOrbs["APT ORB / abandoned apt window"]={OrbSeen=1};
ShownOrbs["APT ORB / foreclosed apt table"]={OrbSeen=1};
ShownOrbs["COAL ORB / coalpile"]={OrbSeen=1};
ShownOrbs["COAL ORB / bed"]={OrbSeen=1};
ShownOrbs["PIER ORB / lockrusted"]={OrbSeen=1};
ShownOrbs["APT ORB / vacated apt door"]={OrbSeen=1};
ShownOrbs["APT ORB / locked apt door"]={OrbSeen=1};
ShownOrbs["APT ORB / communist star on the wall"]={OrbSeen=1};
ShownOrbs["APT ORB / cleaning supplies"]={OrbSeen=1};
ShownOrbs["APT ORB / corkboard"]={OrbSeen=1};
ShownOrbs["APT ORB / hallway boots"]={OrbSeen=1};
ShownOrbs["APT ORB / door to apartment"]={OrbSeen=1};
ShownOrbs["APT ORB / bathroom sink"]={OrbSeen=1};
ShownOrbs["APT ORB / aptbed"]={OrbSeen=1};
ShownOrbs["COAST ORB / radiorelayfinished"]={OrbSeen=1};
ShownOrbs["COAST ORB / wordsonsign"]={OrbSeen=1};
ShownOrbs["COAST ORB / pylonpowerbox"]={OrbSeen=1};
ShownOrbs["COAST ORB / fencehole"]={OrbSeen=1};
ShownOrbs["COAST ORB / summer house swing"]={OrbSeen=1};
ShownOrbs["COAST ORB / gloria"]={OrbSeen=1};
ShownOrbs["COAST ORB / junkmusic"]={OrbSeen=1};
ShownOrbs["COAST ORB / coveredboat"]={OrbSeen=1};
ShownOrbs["COAST ORB / redchair"]={OrbSeen=1};
ShownOrbs["COAST ORB / windowtoinside"]={OrbSeen=1};
ShownOrbs["COAST ORB / bushestoothick"]={OrbSeen=1};
ShownOrbs["COAST ORB / partydrugs"]={OrbSeen=1};
ShownOrbs["COAST ORB / brokenwindowdust"]={OrbSeen=1};
ShownOrbs["COAST ORB / redwindow"]={OrbSeen=1};
ShownOrbs["COAST ORB / whettingstone"]={OrbSeen=1};
ShownOrbs["COAST ORB / forgottenbuild"]={OrbSeen=1};
ShownOrbs["COAST ORB / floatboat"]={OrbSeen=1};
ShownOrbs["VILLAGE ORB / boat"]={OrbSeen=1};
ShownOrbs["COAST ORB / ladderfish"]={OrbSeen=1};
ShownOrbs["COAST ORB / doorrattle"]={OrbSeen=1};
ShownOrbs["COAST ORB / windowangle"]={OrbSeen=1};
ShownOrbs["VILLAGE ORB / illegible street sign"]={OrbSeen=1};
ShownOrbs["COAST ORB / windownetpicker"]={OrbSeen=1};
ShownOrbs["COAST ORB / flowertrough"]={OrbSeen=1};
ShownOrbs["NETHOUSE ORB / fireplace"]={OrbSeen=1};
ShownOrbs["COAST ORB / frozenbottle"]={OrbSeen=1};
ShownOrbs["COAST ORB / rustbarrel"]={OrbSeen=1};
ShownOrbs["COAST ORB / motor carriage tire"]={OrbSeen=1};
ShownOrbs["COAST ORB / fishpost"]={OrbSeen=1};
ShownOrbs["ICE ORB / eternite logic"]={OrbSeen=1};
ShownOrbs["COAST ORB / firststack"]={OrbSeen=1};
ShownOrbs["COAST ORB / firstcheerypost"]={OrbSeen=1};
ShownOrbs["COAST ORB / landfill"]={OrbSeen=1};
ShownOrbs["COAST ORB / poleinice"]={OrbSeen=1};
ShownOrbs["COAST ORB / tribalpaint"]={OrbSeen=1};
ShownOrbs["COAST ORB / northboathouse"]={OrbSeen=1};
ShownOrbs["COAST ORB / boathideout"]={OrbSeen=1};
ShownOrbs["COAST ORB / shadedbench"]={OrbSeen=1};
ShownOrbs["COAST ORB / signtext"]={OrbSeen=1};
ShownOrbs["COAST ORB / tallbooth"]={OrbSeen=1};
ShownOrbs["COAST ORB / barredshut"]={OrbSeen=1};
ShownOrbs["COAST ORB / buoy"]={OrbSeen=1};
ShownOrbs["COAST ORB / garryfireplace"]={OrbSeen=1};
ShownOrbs["COAST ORB / phasmidtrap"]={OrbSeen=1};
ShownOrbs["COAST ORB / blockade"]={OrbSeen=1};
ShownOrbs["COAST ORB / cannotpassfence"]={OrbSeen=1};
ShownOrbs["COAST ORB / feldwindowsbars"]={OrbSeen=1};
ShownOrbs["COAST ORB / dockhome"]={OrbSeen=1};
ShownOrbs["COAST ORB / weighmachine"]={OrbSeen=1};
ShownOrbs["COAST ORB / redtarp"]={OrbSeen=1};
ShownOrbs["COAST ORB / emptyfuelcannister"]={OrbSeen=1};
ShownOrbs["BOARDWALK ORB / coin-operated viewer"]={OrbSeen=1};
ShownOrbs["COAST ORB /  -- smasheddome"]={OrbSeen=1};
