// SPDX-License-Identifier: MIT
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using GlobalConversationTracker.Persistence;
using Xunit;

namespace GlobalConversationTracker.Persistence.Tests
{
    /// <summary>
    /// The <c>.states.lua</c> orb parser. The shape it has to handle is generated by
    /// the game, never hand written, so most of these are pinned against a real save
    /// file where one is available and against the writer's documented shape otherwise.
    /// </summary>
    public class ShownOrbsParserTests
    {
        private const string OneRow =
            "ShownOrbs[\"WHIRLING F2 ORB / locked door\"]={OrbSeen=1};\n";

        [Fact]
        public void ReadsATitle()
        {
            Assert.Equal(
                new[] { "WHIRLING F2 ORB / locked door" },
                ShownOrbsParser.GetSeenOrbTitles(OneRow));
        }

        [Fact]
        public void IgnoresOtherTablesInTheSameFile()
        {
            string file =
                "AreaState[\"CHURCH_AUXWIRE\"]={LocationState=0};\n"
                + OneRow
                + "AreaState[\"DOOMED_DOOR\"]={LocationState=0};\n";

            Assert.Single(ShownOrbsParser.GetSeenOrbTitles(file));
        }

        [Fact]
        public void KeepsTitlesWithSlashesSpacesPunctuationAndCase()
        {
            // Real orb conversation titles: a location prefix, a slash, free text.
            string file =
                "ShownOrbs[\"WHIRLING F1 / SPARE WORKSHOP KEYS\"]={OrbSeen=1};\n"
                + "ShownOrbs[\"COAST ORB / reeds near sunken car\"]={OrbSeen=1};\n"
                + "ShownOrbs[\"JAM ORB / motor lorry ency\"]={OrbSeen=1};\n";

            Assert.Equal(
                new[]
                {
                    "WHIRLING F1 / SPARE WORKSHOP KEYS",
                    "COAST ORB / reeds near sunken car",
                    "JAM ORB / motor lorry ency",
                },
                ShownOrbsParser.GetSeenOrbTitles(file));
        }

        [Fact]
        public void HandlesCarriageReturnsFromAWindowsWrittenFile()
        {
            Assert.Single(ShownOrbsParser.GetSeenOrbTitles(OneRow.Replace("\n", "\r\n")));
        }

        [Fact]
        public void ToleratesWhitespaceTheWriterDoesNotCurrentlyEmit()
        {
            string file = "  ShownOrbs [ \"A / b\" ] = { OrbSeen = 1 } ; \n";

            Assert.Equal(new[] { "A / b" }, ShownOrbsParser.GetSeenOrbTitles(file));
        }

        [Theory]
        [InlineData("ShownOrbs[\"A / b\"]={OrbSeen=0};")]
        [InlineData("ShownOrbs[\"A / b\"]={OrbSeen=2};")]
        [InlineData("ShownOrbs[\"A / b\"]={};")]
        [InlineData("ShownOrbs[\"A / b\"]={SomethingElse=1};")]
        public void SkipsARowThatDoesNotSayTheOrbWasSeen(string row)
        {
            Assert.Empty(ShownOrbsParser.GetSeenOrbTitles(row + "\n"));
        }

        [Fact]
        public void DoesNotMatchOrbSeenAsASubstringOfAnotherField()
        {
            Assert.Empty(
                ShownOrbsParser.GetSeenOrbTitles("ShownOrbs[\"A / b\"]={NotOrbSeen=1};\n"));
        }

        [Fact]
        public void SkipsAnEmptyTitle()
        {
            Assert.Empty(ShownOrbsParser.GetSeenOrbTitles("ShownOrbs[\"\"]={OrbSeen=1};\n"));
        }

        [Theory]
        [InlineData("")]
        [InlineData("\n\n\n")]
        [InlineData("this is not lua at all")]
        [InlineData("ShownOrbs = {};")]
        public void ReturnsNothingRatherThanThrowingOnUnhelpfulInput(string file)
        {
            Assert.Empty(ShownOrbsParser.GetSeenOrbTitles(file));
        }

        [Fact]
        public void NullInput_Throws()
        {
            Assert.Throws<ArgumentNullException>(() => ShownOrbsParser.GetSeenOrbTitles(null!));
        }

        [Fact]
        public void KeepsDuplicatesForTheCallerToAbsorb()
        {
            Assert.Equal(2, ShownOrbsParser.GetSeenOrbTitles(OneRow + OneRow).Count);
        }

        [Theory]
        [InlineData("MySave.states.lua", true)]
        [InlineData(".states.lua", true)]
        [InlineData(".STATES.LUA", true)]
        [InlineData("MySave.ntwtf.lua", false)]
        [InlineData(".FOW.json", false)]
        [InlineData(null, false)]
        public void IsStatesFile_RecognizesTheSuffixOnly(string? name, bool expected)
        {
            Assert.Equal(expected, ShownOrbsParser.IsStatesFile(name));
        }

        // -------------------------------------------------------------------
        // Against a real save, when one is on this machine. Skipped rather than
        // failed elsewhere: the file is a playthrough's, not the repo's.
        // -------------------------------------------------------------------

        [Fact]
        public void ParsesEveryOrbRowOfARealStatesFile()
        {
            string? path = FindARealStatesFile();
            if (path is null)
            {
                return;
            }

            string file = File.ReadAllText(path);
            List<string> titles = ShownOrbsParser.GetSeenOrbTitles(file);

            // Every ShownOrbs row in the file is accounted for - the parser skips none
            // of them - and nothing else in the file is mistaken for one.
            int rowCount = file
                .Split('\n')
                .Count(line => line.TrimStart().StartsWith(
                    ShownOrbsParser.TableName + "[", StringComparison.Ordinal));

            Assert.Equal(rowCount, titles.Count);
            Assert.All(titles, title => Assert.NotEmpty(title));
            Assert.DoesNotContain(titles, title => title.Contains("AreaState", StringComparison.Ordinal));
        }

        private static string? FindARealStatesFile()
        {
            string saves = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
                "AppData", "LocalLow", "ZAUM Studio", "Disco Elysium", "SaveGames");

            if (!Directory.Exists(saves))
            {
                return null;
            }

            return Directory
                .EnumerateFiles(saves, "*" + ShownOrbsParser.StatesFileSuffix,
                    SearchOption.AllDirectories)
                .FirstOrDefault();
        }
    }
}
