// SPDX-License-Identifier: MIT
using System;
using System.IO;
using System.Threading;

namespace GlobalConversationTracker.Persistence
{
    /// <summary>
    /// Reads and writes the global conversation state as a single fixed-name JSON
    /// file in the game's SaveGames directory, durably.
    /// </summary>
    /// <remarks>
    /// <para>Takes the directory as a string rather than calling Unity, so it stays
    /// testable and free of game dependencies; the plugin resolves it through
    /// <c>SaveGameDirectory.Resolve</c>. Trailing separators are normalized by the
    /// constructor.</para>
    ///
    /// <para>The durability contract. The global state is the only copy of cross-save
    /// history and cannot be regenerated by replaying the game, so a save never writes
    /// the live file in place. <see cref="Save"/> writes a complete temp file in the
    /// same directory, flushes it to disk, renames the live file over the backup slot,
    /// then renames the temp file over the live path. At no point do zero complete files
    /// exist: before the rotation the old live file is intact, and from the rotation
    /// onward the backup holds the previous generation while the temp file holds the new
    /// one. Both renames are same-directory, so they are metadata operations.</para>
    ///
    /// <para>Not thread safe, and it does not need to be - but only one thread may be
    /// inside <see cref="Save"/> or <see cref="SavePayload"/> at a time: two concurrent
    /// saves would share one <see cref="TempPath"/> and race over the two renames, which
    /// is the one way this type could lose a generation. <c>GlobalStateSession</c>
    /// guarantees that by writing on a single background thread.</para>
    /// </remarks>
    public sealed class GlobalStateStore
    {
        /// <summary>
        /// The file name a player always gets, per ProjectGoal.md ("for initial
        /// implementation, the name of the save file should be constant /
        /// unalterable").
        /// </summary>
        /// <remarks>
        /// Constant in every case the mod is played in. The one exception is
        /// <see cref="GlobalStatePath.OverrideVariable"/>, an environment variable that
        /// exists so a build under test can be pointed away from the real global state -
        /// the only file here that cannot be regenerated, being the record of every
        /// playthrough. It is not reachable from the config a player edits.
        /// </remarks>
        public const string FileName = "global-conversation-state.json";

        /// <summary>Suffix of the previous generation kept beside the live file.</summary>
        public const string BackupSuffix = ".bak";

        /// <summary>Suffix of the in-progress write, promoted by rename when complete.</summary>
        public const string TempSuffix = ".tmp";

        private const int DefaultWriteChunkSize = int.MaxValue;

        /// <summary>
        /// Payload bytes written per <c>Write</c> call. Effectively one call in
        /// production; tests shrink it so a crash point exists inside the write.
        /// </summary>
        internal int WriteChunkSize { get; set; } = DefaultWriteChunkSize;

        /// <summary>
        /// Invoked after each step of <see cref="Save"/>. Tests use it to stop the
        /// process dead at a chosen step. Null in production, and there is
        /// deliberately no cleanup or rollback anywhere in <see cref="Save"/>, so a
        /// hook that throws leaves the directory in exactly the state a real crash
        /// would.
        /// </summary>
        internal Action<GlobalStateSaveStep>? SaveStepHook { get; set; }

        /// <summary>
        /// Creates a store over the given directory. The directory is not touched
        /// until a save; loading a file from a directory that does not exist simply
        /// reports <see cref="GlobalStateLoadOutcome.Missing"/>.
        /// </summary>
        /// <param name="saveGameDirectory">
        /// The SaveGames directory, with or without a trailing separator.
        /// </param>
        /// <exception cref="ArgumentException">
        /// <paramref name="saveGameDirectory"/> is null, empty or whitespace.
        /// </exception>
        public GlobalStateStore(string saveGameDirectory)
        {
            DirectoryPath = NormalizeDirectory(saveGameDirectory);
            LivePath = Path.Combine(DirectoryPath, FileName);
            BackupPath = LivePath + BackupSuffix;
            TempPath = LivePath + TempSuffix;
        }

        /// <summary>
        /// Creates a store over a specific file, whose directory need not be the
        /// SaveGames one. For <see cref="GlobalStatePath.OverrideVariable"/>.
        /// </summary>
        /// <param name="filePath">Full path of the live file.</param>
        /// <param name="ignored">
        /// Distinguishes this from the directory constructor, which would otherwise have
        /// the same signature. Its value is never read.
        /// </param>
        /// <exception cref="ArgumentException">
        /// <paramref name="filePath"/> is null, empty, whitespace, or names no directory.
        /// </exception>
        private GlobalStateStore(string filePath, bool ignored)
        {
            if (string.IsNullOrWhiteSpace(filePath))
            {
                throw new ArgumentException(
                    "The global state path must not be empty.", nameof(filePath));
            }

            string? directory = Path.GetDirectoryName(filePath);
            if (string.IsNullOrWhiteSpace(directory))
            {
                throw new ArgumentException(
                    $"'{filePath}' names no directory to write into.", nameof(filePath));
            }

            DirectoryPath = NormalizeDirectory(directory!);
            LivePath = filePath;
            BackupPath = LivePath + BackupSuffix;
            TempPath = LivePath + TempSuffix;
        }

        /// <summary>Creates a store over a specific file path.</summary>
        /// <param name="filePath">
        /// Full path of the live file. Its directory carries the backup and temp files
        /// too, exactly as the SaveGames directory does by default.
        /// </param>
        /// <exception cref="ArgumentException">
        /// <paramref name="filePath"/> is null, empty, whitespace, or names no directory.
        /// </exception>
        public static GlobalStateStore AtPath(string filePath)
        {
            return new GlobalStateStore(filePath, ignored: true);
        }

        /// <summary>The directory holding all three files, without a trailing separator.</summary>
        public string DirectoryPath { get; }

        /// <summary>Full path of the live file: the current global state.</summary>
        public string LivePath { get; }

        /// <summary>Full path of the backup file: the previous generation.</summary>
        public string BackupPath { get; }

        /// <summary>
        /// Full path of the temp file. Never trusted on load, because a file at this
        /// path may be a half-written payload from a crash.
        /// </summary>
        public string TempPath { get; }

        /// <summary>
        /// Strips trailing directory separators from a directory path.
        /// <c>SunshinePersistenceFileManager.GetSaveGameDirectoryPath()</c> returns
        /// <c>".../SaveGames/"</c>, and joining a file name onto that unnormalized is
        /// how doubled separators get into paths.
        /// </summary>
        /// <exception cref="ArgumentException">
        /// <paramref name="directory"/> is null, empty or whitespace.
        /// </exception>
        public static string NormalizeDirectory(string directory)
        {
            if (string.IsNullOrWhiteSpace(directory))
            {
                throw new ArgumentException("Save game directory must not be empty.", nameof(directory));
            }

            string trimmed = directory.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

            // A root such as "C:\" or "/" is all separator and must keep it.
            return trimmed.Length == 0 ? directory : trimmed;
        }

        // -------------------------------------------------------------------
        // Loading
        // -------------------------------------------------------------------

        /// <summary>Reads the live file.</summary>
        /// <returns>
        /// <see cref="GlobalStateLoadOutcome.Missing"/> when there is no file yet
        /// (a first run), <see cref="GlobalStateLoadOutcome.Corrupt"/> when a file
        /// is there but unreadable, and never an exception for either.
        /// </returns>
        public GlobalStateLoadResult Load() => LoadFile(LivePath);

        /// <summary>Reads the backup file.</summary>
        public GlobalStateLoadResult LoadBackup() => LoadFile(BackupPath);

        /// <summary>
        /// Reads the live file and, if that did not produce a state, falls back to
        /// the backup generation.
        /// </summary>
        /// <remarks>
        /// The backup is consulted when the live file is
        /// <see cref="GlobalStateLoadOutcome.Missing"/> (a crash between the
        /// rotation and the promotion) or <see cref="GlobalStateLoadOutcome.Corrupt"/>.
        /// It is deliberately <b>not</b> consulted for
        /// <see cref="GlobalStateLoadOutcome.UnsupportedVersion"/> or
        /// <see cref="GlobalStateLoadOutcome.OutdatedVersion"/>: that file is intact
        /// history this build will not read, and silently reverting to another
        /// generation would be the same as throwing it away.
        /// <para>
        /// The temp file is never consulted, even though a crash can leave a complete
        /// one. Its name carries no proof of completeness, and a half-written payload
        /// sits at the same path.
        /// </para>
        /// </remarks>
        public GlobalStateRecovery LoadWithBackupFallback()
        {
            GlobalStateLoadResult live = Load();
            if (live.IsLoaded || live.IsRefusedFormat)
            {
                return new GlobalStateRecovery(live, null);
            }

            return new GlobalStateRecovery(live, LoadBackup());
        }

        private static GlobalStateLoadResult LoadFile(string path)
        {
            byte[] bytes;
            try
            {
                if (!File.Exists(path))
                {
                    return GlobalStateLoadResult.Missing(path);
                }

                bytes = File.ReadAllBytes(path);
            }
            catch (FileNotFoundException)
            {
                return GlobalStateLoadResult.Missing(path);
            }
            catch (DirectoryNotFoundException)
            {
                return GlobalStateLoadResult.Missing(path);
            }
            catch (IOException ex)
            {
                // Unreadable for an environmental reason (locked, bad sector). Not
                // "missing", and not something a backup swap should paper over silently,
                // but the caller still gets to decide rather than eating an exception
                // mid-frame.
                return GlobalStateLoadResult.Corrupt(path, $"Could not read file: {ex.Message}");
            }
            catch (UnauthorizedAccessException ex)
            {
                return GlobalStateLoadResult.Corrupt(path, $"Could not read file: {ex.Message}");
            }

            return GlobalStateJson.Deserialize(bytes, path);
        }

        // -------------------------------------------------------------------
        // Saving
        // -------------------------------------------------------------------

        /// <summary>
        /// Writes the state durably: complete temp file, flush, rotate live to
        /// backup, rename temp over live.
        /// </summary>
        /// <remarks>
        /// The existing live file is never opened for writing and never read, so a
        /// failure part way through can only leave the previous generation or the new
        /// one, never a mixture. There is intentionally no try/catch and no cleanup:
        /// an exception must leave the same bytes on disk that a process kill would,
        /// which is what makes the crash-point tests meaningful.
        /// </remarks>
        /// <param name="state">The state to persist.</param>
        /// <exception cref="ArgumentNullException"><paramref name="state"/> is null.</exception>
        /// <exception cref="IOException">The directory or files could not be written.</exception>
        public void Save(GlobalConversationState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException(nameof(state));
            }

            SavePayload(GlobalStateJson.SerializeToUtf8Bytes(state));
        }

        /// <summary>
        /// The file half of <see cref="Save"/>: everything from
        /// <see cref="Directory.CreateDirectory(string)"/> onwards, for a payload that
        /// has already been serialized.
        /// </summary>
        /// <remarks>
        /// Split from <see cref="Save"/> because the two halves have different costs and
        /// different thread-safety needs: serializing reads a state, while the write
        /// (~85% of a save at realistic sizes, almost all of it the flush and the two
        /// renames) touches nothing but the filesystem. <c>GlobalStateSession</c> copies
        /// its state under its lock, then serializes and calls this outside it.
        /// </remarks>
        /// <param name="payload">The serialized state, as it will appear on disk.</param>
        /// <exception cref="ArgumentNullException"><paramref name="payload"/> is null.</exception>
        /// <exception cref="IOException">The directory or files could not be written.</exception>
        public void SavePayload(byte[] payload)
        {
            if (payload == null)
            {
                throw new ArgumentNullException(nameof(payload));
            }

            Directory.CreateDirectory(DirectoryPath);
            Retrying(() => WriteTempFile(payload));
            SaveStepHook?.Invoke(GlobalStateSaveStep.AfterTempFlushed);

            if (File.Exists(LivePath))
            {
                // Single overwriting rename rather than delete-then-move: there is no
                // instant where both the old backup and the live file are gone.
                Retrying(() => File.Move(LivePath, BackupPath, overwrite: true));
                SaveStepHook?.Invoke(GlobalStateSaveStep.AfterLiveRotatedToBackup);
            }

            // LivePath does not exist here, either because the rotation just moved it
            // away or because this is the first save (or a previous crash landed in the
            // window above, in which case the backup still holds the older generation
            // and is deliberately left alone).
            Retrying(() => File.Move(TempPath, LivePath));
            SaveStepHook?.Invoke(GlobalStateSaveStep.AfterTempPromoted);
        }

        /// <summary>
        /// How many times one step of a save is attempted before its failure is reported.
        /// </summary>
        /// <remarks>
        /// The whole budget is well under a second, against a write that costs about 40 ms
        /// at the largest constructible file and a caller that waits 30 seconds for one. It
        /// is sized for a scanner holding a newly created file for a moment, which is what
        /// this is for - not for a network share that has gone away.
        /// </remarks>
        internal const int SaveAttempts = 10;

        /// <summary>How long to wait between attempts, in milliseconds.</summary>
        internal static int SaveRetryDelayMilliseconds { get; set; } = 50;

        /// <summary>
        /// Runs one step of a save, trying again while the failure is one that clears.
        /// </summary>
        /// <remarks>
        /// <para>PER STEP, NOT PER SAVE, and that is the whole design. A save writes the
        /// temporary file, rotates the live file onto the backup, then promotes the
        /// temporary one - and the rotation is NOT IDEMPOTENT. Retrying the sequence after
        /// the rotation had already succeeded would rotate a second time and throw away a
        /// generation, turning a transient lock into real data loss.</para>
        ///
        /// <para>ONLY WHAT CLEARS IS RETRIED. A permission error on the directory is not
        /// going to go away, and retrying it turns an immediate honest failure into a slow
        /// one. See <see cref="IsTransient"/> for what counts.</para>
        ///
        /// <para>The save-step hooks are deliberately OUTSIDE this, so a test that stops a
        /// save dead at a chosen step is not quietly retried into completing. The one hook
        /// that is inside - the mid-write one - throws something this does not consider
        /// transient, so it is not retried either.</para>
        /// </remarks>
        private static void Retrying(Action step)
        {
            for (int attempt = 1; ; attempt++)
            {
                try
                {
                    step();
                    return;
                }
                catch (Exception error) when (attempt < SaveAttempts && IsTransient(error))
                {
                    Thread.Sleep(SaveRetryDelayMilliseconds);
                }
            }
        }

        /// <summary>
        /// Whether a failure is the kind that goes away on its own.
        /// </summary>
        /// <remarks>
        /// <para>A sharing or lock violation, and nothing else. Something else on the
        /// machine held the file for an instant - a virus scanner or a search indexer
        /// noticing a newly created one, a backup agent reading it - and a moment later it
        /// will not. Every other IO failure is either permanent or means something is wrong
        /// that a retry would only delay finding out about.</para>
        ///
        /// <para>The codes are read out of the low half of the HRESULT, which is where
        /// Windows puts the Win32 error: 32 is ERROR_SHARING_VIOLATION and 33 is
        /// ERROR_LOCK_VIOLATION. Neither has a named constant in the BCL.</para>
        /// </remarks>
        /// <param name="error">The failure.</param>
        internal static bool IsTransient(Exception error)
        {
            const int SharingViolation = 32;
            const int LockViolation = 33;

            // Only IOException: an UnauthorizedAccessException here is a permission
            // problem, and the one case where Windows raises it for a file pending
            // deletion is not one a retry of the same operation recovers from.
            if (error is not IOException)
            {
                return false;
            }

            int code = error.HResult & 0xFFFF;
            return code == SharingViolation || code == LockViolation;
        }

        private void WriteTempFile(byte[] payload)
        {
            // FileMode.Create truncates any stale temp file left by an earlier crash.
            using var stream = new FileStream(
                TempPath,
                FileMode.Create,
                FileAccess.Write,
                FileShare.None);

            int chunkSize = Math.Max(1, WriteChunkSize);
            int offset = 0;
            while (offset < payload.Length)
            {
                int count = Math.Min(chunkSize, payload.Length - offset);
                stream.Write(payload, offset, count);
                offset += count;

                if (offset < payload.Length)
                {
                    // Push what has been written so far out of the managed buffer, so a
                    // crash at this point really does leave a partial file on disk rather
                    // than nothing at all.
                    stream.Flush();
                    SaveStepHook?.Invoke(GlobalStateSaveStep.DuringTempWrite);
                }
            }

            // flushToDisk: the rename that follows must not be able to reach the disk
            // ahead of the bytes it is promoting.
            stream.Flush(flushToDisk: true);
        }
    }
}
