// SPDX-License-Identifier: MIT
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;

namespace GlobalConversationTracker.Persistence
{
    /// <summary>
    /// The one reader and writer of the state file, which is native and is linked in.
    /// </summary>
    /// <remarks>
    /// <para>WHY THIS IS LINKED AND NOT SPAWNED. Every other format this repository defines
    /// is reached from C# by running <c>gct-engine-host</c>, which suits a tool: a tool that
    /// cannot start a process has failed at something it can report. The state file is not
    /// like that. It is the only copy of cross-save history, it cannot be regenerated by
    /// replaying the game, and it is read and written from inside a running game whose mod
    /// promises that an engine failing to start costs a capability rather than a
    /// playthrough. A library that is simply there has no absent process to answer for.</para>
    ///
    /// <para>WHY IT IS NOT A SECOND IMPLEMENTATION. Because that is the arrangement this
    /// repository has paid for twice: a fact stated twice drifts, and the half that drifts is
    /// whichever one no test happens to exercise. There is one reader and one writer of this
    /// format, in <c>gct_formats::global_state</c>, and this is how the game reaches it.</para>
    ///
    /// <para>WHAT CROSSES. A state is entries and orbs: reading hands back a flat array of
    /// conversation, entry and status, plus the titles; writing takes the same and hands back
    /// the bytes. The worst case this repository holds is 113,000 entries, about 1.3 MB of
    /// array once per load and once per save, which does not justify a chattier interface.
    /// Durability does not cross at all - see <see cref="GlobalStateStore"/>, which keeps
    /// it.</para>
    /// </remarks>
    internal static class GlobalStateNative
    {
        /// <summary>What the library is called, without platform decoration.</summary>
        private const string LibraryName = "gct_state";

        /// <summary>What to run to build it, which is what a failure says to do.</summary>
        internal const string BuildCommand = "cargo build --release -p gct_state";

        /// <summary>
        /// Registered once, so the library is found beside this assembly.
        /// </summary>
        /// <remarks>
        /// The default search looks beside the PROCESS, and the process is the game - whose
        /// directory is not where a BepInEx plugin and its dependencies are installed. So the
        /// place to look is beside this assembly, which is wherever the mod was put.
        ///
        /// Declaring it explicitly rather than as a field initializer is what makes the type
        /// not <c>beforefieldinit</c>, which is what guarantees this has run before the first
        /// call through any of the declarations below.
        /// </remarks>
        static GlobalStateNative()
        {
            NativeLibrary.SetDllImportResolver(
                typeof(GlobalStateNative).Assembly, ResolveBesideThisAssembly);
        }

        private static IntPtr ResolveBesideThisAssembly(
            string name, Assembly assembly, DllImportSearchPath? path)
        {
            if (name != LibraryName)
            {
                return IntPtr.Zero;
            }

            string? beside = Path.GetDirectoryName(assembly.Location);
            if (string.IsNullOrEmpty(beside))
            {
                return IntPtr.Zero;
            }

            foreach (string candidate in Candidates(beside!, name))
            {
                if (File.Exists(candidate)
                    && NativeLibrary.TryLoad(candidate, out IntPtr loaded))
                {
                    return loaded;
                }
            }

            // Nothing beside us; let the ordinary search have its turn, which is what finds
            // it when a test runner has copied it somewhere else.
            return IntPtr.Zero;
        }

        /// <summary>What the library is called on each platform this may run on.</summary>
        private static IEnumerable<string> Candidates(string beside, string name)
        {
            yield return Path.Combine(beside, name + ".dll");
            yield return Path.Combine(beside, "lib" + name + ".so");
            yield return Path.Combine(beside, "lib" + name + ".dylib");
        }

        /// <summary>One entry of a state, as it crosses.</summary>
        [StructLayout(LayoutKind.Sequential)]
        internal struct Entry
        {
            public int Conversation;
            public int DialogueEntry;

            /// <summary>
            /// The status, numbered as <c>SimStatus</c> numbers it.
            /// </summary>
            /// <remarks>
            /// The two numberings agreeing is not a coincidence to rely on quietly - a test
            /// pins it, because a silent disagreement would rewrite every status in the file.
            /// </remarks>
            public int Status;
        }

        /// <summary>The document read, and everything that would not.</summary>
        internal const int OutcomeLoaded = 0;

        /// <summary>It will not parse, or leaves out what a state must say.</summary>
        internal const int OutcomeCorrupt = 1;

        /// <summary>It is another kind of document, or another version of this one.</summary>
        internal const int OutcomeUnsupported = 2;

        [DllImport(LibraryName, EntryPoint = "gct_state_read")]
        internal static extern unsafe IntPtr Read(byte* json, nuint length);

        [DllImport(LibraryName, EntryPoint = "gct_state_outcome")]
        internal static extern int Outcome(IntPtr read);

        [DllImport(LibraryName, EntryPoint = "gct_state_message")]
        internal static extern IntPtr Message(IntPtr read, out nuint length);

        [DllImport(LibraryName, EntryPoint = "gct_state_skipped")]
        internal static extern nuint Skipped(IntPtr read);

        [DllImport(LibraryName, EntryPoint = "gct_state_warning_count")]
        internal static extern nuint WarningCount(IntPtr read);

        [DllImport(LibraryName, EntryPoint = "gct_state_warning")]
        internal static extern IntPtr Warning(IntPtr read, nuint at, out nuint length);

        [DllImport(LibraryName, EntryPoint = "gct_state_entry_count")]
        internal static extern nuint EntryCount(IntPtr read);

        [DllImport(LibraryName, EntryPoint = "gct_state_entries")]
        internal static extern unsafe nuint Entries(IntPtr read, Entry* into, nuint capacity);

        [DllImport(LibraryName, EntryPoint = "gct_state_orb_count")]
        internal static extern nuint OrbCount(IntPtr read);

        [DllImport(LibraryName, EntryPoint = "gct_state_orb")]
        internal static extern IntPtr Orb(IntPtr read, nuint at, out nuint length);

        [DllImport(LibraryName, EntryPoint = "gct_state_read_free")]
        internal static extern void FreeRead(IntPtr read);

        [DllImport(LibraryName, EntryPoint = "gct_state_write")]
        internal static extern unsafe IntPtr Write(
            Entry* entries,
            nuint count,
            byte* orbText,
            nuint orbTextLength,
            nuint* orbLengths,
            nuint orbCount);

        [DllImport(LibraryName, EntryPoint = "gct_state_bytes")]
        internal static extern IntPtr Bytes(IntPtr written, out nuint length);

        [DllImport(LibraryName, EntryPoint = "gct_state_bytes_free")]
        internal static extern void FreeBytes(IntPtr written);

        [DllImport(LibraryName, EntryPoint = "gct_state_format_name")]
        internal static extern IntPtr FormatName(out nuint length);

        [DllImport(LibraryName, EntryPoint = "gct_state_format_version")]
        internal static extern uint FormatVersion();

        [DllImport(LibraryName, EntryPoint = "gct_state_max_warnings")]
        internal static extern nuint MaxWarnings();

        /// <summary>One string the library handed out, copied into managed memory.</summary>
        /// <remarks>
        /// COPIED, and that is the point: everything the library returns belongs to the
        /// handle it came from and is gone the moment that handle is freed.
        /// </remarks>
        internal static string TextAt(IntPtr first, nuint length)
        {
            if (first == IntPtr.Zero || length == 0)
            {
                return string.Empty;
            }

            return Marshal.PtrToStringUTF8(first, checked((int)length)) ?? string.Empty;
        }
    }
}
