// SPDX-License-Identifier: MIT
using System;
using System.IO;

namespace GlobalConversationTracker.Persistence
{
    /// <summary>
    /// Reads and writes the global conversation state as a single fixed-name JSON
    /// file in the game's SaveGames directory, durably.
    /// </summary>
    /// <remarks>
    /// <para><b>Where the directory comes from.</b> This type takes the directory as a
    /// string rather than calling Unity, so it stays testable and free of game
    /// dependencies. The plugin resolves it with:</para>
    /// <code>
    /// string saveDir;
    /// try { saveDir = SunshinePersistenceFileManager.GetSaveGameDirectoryPath(); }
    /// catch { saveDir = Path.Combine(UnityEngine.Application.persistentDataPath, "SaveGames"); }
    /// var store = new GlobalStateStore(saveDir);
    /// </code>
    /// <para>
    /// That call returns a path with a trailing slash; the constructor normalizes
    /// trailing separators itself, so passing it straight through is fine. Call it
    /// from plugin <c>Load()</c> or later, never from a static initializer that runs
    /// before BepInEx finishes chainloading.
    /// </para>
    /// <para><b>The durability contract.</b> The global state is the only copy of
    /// cross-save history and cannot be regenerated by replaying the game, so a save
    /// never writes the live file in place. <see cref="Save"/> writes a complete temp
    /// file in the same directory, flushes it to disk, renames the current live file
    /// over the backup slot, then renames the temp file over the live path. At no
    /// point in that sequence do zero complete files exist: before the rotation the
    /// old live file is intact, and from the rotation onward the backup holds the
    /// previous generation while the temp file holds the new one. Both renames are
    /// same-directory, so they are metadata operations rather than copies.</para>
    /// <para>
    /// Not thread safe, and it does not need to be: ProjectGoal.md assumes a single
    /// running game, and the on-disk copy is never read before overwriting. What it
    /// does require is that only one thread is inside <see cref="Save"/> or
    /// <see cref="SavePayload"/> at a time - two concurrent saves would share one
    /// <see cref="TempPath"/> and race over the two renames, which is the one way
    /// this type could lose a generation. <c>GlobalStateSession</c> guarantees that
    /// by doing every write on a single background thread.
    /// </para>
    /// </remarks>
    public sealed class GlobalStateStore
    {
        /// <summary>
        /// The fixed, non-configurable file name, per ProjectGoal.md ("the name of
        /// the save file should be constant / unalterable").
        /// </summary>
        public const string FileName = "global-conversation-state.json";

        /// <summary>Suffix of the previous generation kept beside the live file.</summary>
        public const string BackupSuffix = ".bak";

        /// <summary>Suffix of the in-progress write, promoted by rename when complete.</summary>
        public const string TempSuffix = ".tmp";

        private const int DefaultWriteChunkSize = int.MaxValue;

        /// <summary>
        /// Payload bytes written per <c>Write</c> call. Effectively one call in
        /// production; tests shrink it so a crash point exists inside the write.
        /// </summary>
        internal int WriteChunkSize { get; set; } = DefaultWriteChunkSize;

        /// <summary>
        /// Invoked after each step of <see cref="Save"/>. Tests use it to stop the
        /// process dead at a chosen step. Null in production, and there is
        /// deliberately no cleanup or rollback anywhere in <see cref="Save"/>, so a
        /// hook that throws leaves the directory in exactly the state a real crash
        /// would.
        /// </summary>
        internal Action<GlobalStateSaveStep>? SaveStepHook { get; set; }

        /// <summary>
        /// Creates a store over the given directory. The directory is not touched
        /// until a save; loading a file from a directory that does not exist simply
        /// reports <see cref="GlobalStateLoadOutcome.Missing"/>.
        /// </summary>
        /// <param name="saveGameDirectory">
        /// The SaveGames directory, with or without a trailing separator.
        /// </param>
        /// <exception cref="ArgumentException">
        /// <paramref name="saveGameDirectory"/> is null, empty or whitespace.
        /// </exception>
        public GlobalStateStore(string saveGameDirectory)
        {
            DirectoryPath = NormalizeDirectory(saveGameDirectory);
            LivePath = Path.Combine(DirectoryPath, FileName);
            BackupPath = LivePath + BackupSuffix;
            TempPath = LivePath + TempSuffix;
        }

        /// <summary>The directory holding all three files, without a trailing separator.</summary>
        public string DirectoryPath { get; }

        /// <summary>Full path of the live file: the current global state.</summary>
        public string LivePath { get; }

        /// <summary>Full path of the backup file: the previous generation.</summary>
        public string BackupPath { get; }

        /// <summary>
        /// Full path of the temp file. Never trusted on load, because a file at this
        /// path may be a half-written payload from a crash.
        /// </summary>
        public string TempPath { get; }

        /// <summary>
        /// Strips trailing directory separators from a directory path.
        /// <c>SunshinePersistenceFileManager.GetSaveGameDirectoryPath()</c> returns
        /// <c>".../SaveGames/"</c>, and joining a file name onto that unnormalized is
        /// how doubled separators get into paths.
        /// </summary>
        /// <exception cref="ArgumentException">
        /// <paramref name="directory"/> is null, empty or whitespace.
        /// </exception>
        public static string NormalizeDirectory(string directory)
        {
            if (string.IsNullOrWhiteSpace(directory))
            {
                throw new ArgumentException("Save game directory must not be empty.", nameof(directory));
            }

            string trimmed = directory.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

            // A root such as "C:\" or "/" is all separator and must keep it.
            return trimmed.Length == 0 ? directory : trimmed;
        }

        // -------------------------------------------------------------------
        // Loading
        // -------------------------------------------------------------------

        /// <summary>Reads the live file.</summary>
        /// <returns>
        /// <see cref="GlobalStateLoadOutcome.Missing"/> when there is no file yet
        /// (a first run), <see cref="GlobalStateLoadOutcome.Corrupt"/> when a file
        /// is there but unreadable, and never an exception for either.
        /// </returns>
        public GlobalStateLoadResult Load() => LoadFile(LivePath);

        /// <summary>Reads the backup file.</summary>
        public GlobalStateLoadResult LoadBackup() => LoadFile(BackupPath);

        /// <summary>
        /// Reads the live file and, if that did not produce a state, falls back to
        /// the backup generation.
        /// </summary>
        /// <remarks>
        /// The backup is consulted when the live file is
        /// <see cref="GlobalStateLoadOutcome.Missing"/> (a crash between the
        /// rotation and the promotion) or <see cref="GlobalStateLoadOutcome.Corrupt"/>.
        /// It is deliberately <b>not</b> consulted for
        /// <see cref="GlobalStateLoadOutcome.UnsupportedVersion"/>: that file is
        /// intact history written by a newer build, and silently reverting to an
        /// older generation would be the same as throwing it away.
        /// <para>
        /// The temp file is never consulted, even though a crash can leave a complete
        /// one. Its name carries no proof of completeness, and a half-written payload
        /// sits at the same path.
        /// </para>
        /// </remarks>
        public GlobalStateRecovery LoadWithBackupFallback()
        {
            GlobalStateLoadResult live = Load();
            if (live.IsLoaded || live.Outcome == GlobalStateLoadOutcome.UnsupportedVersion)
            {
                return new GlobalStateRecovery(live, null);
            }

            return new GlobalStateRecovery(live, LoadBackup());
        }

        private static GlobalStateLoadResult LoadFile(string path)
        {
            byte[] bytes;
            try
            {
                if (!File.Exists(path))
                {
                    return GlobalStateLoadResult.Missing(path);
                }

                bytes = File.ReadAllBytes(path);
            }
            catch (FileNotFoundException)
            {
                return GlobalStateLoadResult.Missing(path);
            }
            catch (DirectoryNotFoundException)
            {
                return GlobalStateLoadResult.Missing(path);
            }
            catch (IOException ex)
            {
                // Unreadable for an environmental reason (locked, bad sector). Not
                // "missing", and not something a backup swap should paper over silently,
                // but the caller still gets to decide rather than eating an exception
                // mid-frame.
                return GlobalStateLoadResult.Corrupt(path, $"Could not read file: {ex.Message}");
            }
            catch (UnauthorizedAccessException ex)
            {
                return GlobalStateLoadResult.Corrupt(path, $"Could not read file: {ex.Message}");
            }

            return GlobalStateJson.Deserialize(bytes, path);
        }

        // -------------------------------------------------------------------
        // Saving
        // -------------------------------------------------------------------

        /// <summary>
        /// Writes the state durably: complete temp file, flush, rotate live to
        /// backup, rename temp over live.
        /// </summary>
        /// <remarks>
        /// The existing live file is never opened for writing and never read, so a
        /// failure part way through can only leave the previous generation or the new
        /// one, never a mixture. There is intentionally no try/catch and no cleanup:
        /// an exception must leave the same bytes on disk that a process kill would,
        /// which is what makes the crash-point tests meaningful.
        /// </remarks>
        /// <param name="state">The state to persist.</param>
        /// <exception cref="ArgumentNullException"><paramref name="state"/> is null.</exception>
        /// <exception cref="IOException">The directory or files could not be written.</exception>
        public void Save(GlobalConversationState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException(nameof(state));
            }

            SavePayload(GlobalStateJson.SerializeToUtf8Bytes(state));
        }

        /// <summary>
        /// The file half of <see cref="Save"/>: everything from
        /// <see cref="Directory.CreateDirectory(string)"/> onwards, for a payload that
        /// has already been serialized.
        /// </summary>
        /// <remarks>
        /// Serializing a state and writing the bytes have very different costs and
        /// very different thread-safety needs: serializing reads a state, while the
        /// write - which is ~85% of a save at realistic sizes, almost all of it the
        /// flush and the two renames - touches nothing but the filesystem.
        /// A caller that has both halves can only put them on different threads, or
        /// inside and outside a lock, if it can drive them separately.
        /// <c>GlobalStateSession</c> does both: it copies its state under its lock and
        /// then serializes and calls this outside it.
        /// </remarks>
        /// <param name="payload">The serialized state, as it will appear on disk.</param>
        /// <exception cref="ArgumentNullException"><paramref name="payload"/> is null.</exception>
        /// <exception cref="IOException">The directory or files could not be written.</exception>
        public void SavePayload(byte[] payload)
        {
            if (payload == null)
            {
                throw new ArgumentNullException(nameof(payload));
            }

            Directory.CreateDirectory(DirectoryPath);
            WriteTempFile(payload);
            SaveStepHook?.Invoke(GlobalStateSaveStep.AfterTempFlushed);

            if (File.Exists(LivePath))
            {
                // Single overwriting rename rather than delete-then-move: there is no
                // instant where both the old backup and the live file are gone.
                File.Move(LivePath, BackupPath, overwrite: true);
                SaveStepHook?.Invoke(GlobalStateSaveStep.AfterLiveRotatedToBackup);
            }

            // LivePath does not exist here, either because the rotation just moved it
            // away or because this is the first save (or a previous crash landed in the
            // window above, in which case the backup still holds the older generation
            // and is deliberately left alone).
            File.Move(TempPath, LivePath);
            SaveStepHook?.Invoke(GlobalStateSaveStep.AfterTempPromoted);
        }

        private void WriteTempFile(byte[] payload)
        {
            // FileMode.Create truncates any stale temp file left by an earlier crash.
            using var stream = new FileStream(
                TempPath,
                FileMode.Create,
                FileAccess.Write,
                FileShare.None);

            int chunkSize = Math.Max(1, WriteChunkSize);
            int offset = 0;
            while (offset < payload.Length)
            {
                int count = Math.Min(chunkSize, payload.Length - offset);
                stream.Write(payload, offset, count);
                offset += count;

                if (offset < payload.Length)
                {
                    // Push what has been written so far out of the managed buffer, so a
                    // crash at this point really does leave a partial file on disk rather
                    // than nothing at all.
                    stream.Flush();
                    SaveStepHook?.Invoke(GlobalStateSaveStep.DuringTempWrite);
                }
            }

            // flushToDisk: the rename that follows must not be able to reach the disk
            // ahead of the bytes it is promoting.
            stream.Flush(flushToDisk: true);
        }
    }
}
