// SPDX-License-Identifier: MIT
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using GlobalConversationTracker.Core;
using GlobalConversationTracker.Persistence;
using Xunit;

namespace GlobalConversationTracker.Automation.Tests
{
    /// <summary>
    /// Every committed state fixture reads, and writes back as the bytes it came from.
    /// </summary>
    /// <remarks>
    /// <para>THIS FORMAT IS READ BY TWO PROGRAMS ON PURPOSE, which is the arrangement every
    /// other format in this repository has been moved away from. The reason is written down
    /// on de-xz48.6.5.3 and comes to this: the state file is the only copy of cross-save
    /// history, it cannot be regenerated by replaying the game, and the mod is built so that
    /// a look-ahead engine which will not start costs a capability rather than a
    /// playthrough. Putting the only writer of that file behind that process would make an
    /// engine that dies mid-session into a session that loses what it read.</para>
    ///
    /// <para>So the two implementations stay, and what removes the drift is this: BOTH ARE
    /// PINNED TO THE SAME COMMITTED FILES. This reads each one with
    /// <see cref="GlobalStateJson"/> and writes it back, comparing bytes;
    /// <c>tests/committed_states.rs</c> does exactly the same with the engine's
    /// <c>formats::global_state</c>. Neither can change what it writes without one of the
    /// two failing, and a fixture cannot be updated to suit one of them without the other
    /// saying so.</para>
    ///
    /// <para>A fixture written as a CHANGE to another one is not compared here. Resolving
    /// one needs the engine host, and a check on the format should not need a cargo build to
    /// run; the engine's own test resolves those.</para>
    /// </remarks>
    public class CommittedStateFixtureTests
    {
        /// <summary>
        /// How many whole state fixtures the repository is known to carry.
        /// </summary>
        /// <remarks>
        /// A LOWER BOUND, so a test finding none - a moved directory, a filter that stopped
        /// matching - fails rather than passing over an empty list.
        /// </remarks>
        private const int AtLeast = 14;

        private static string ScenarioRoot =>
            Path.Combine(GameInstall.RepoRoot(), "testing", "scenarios");

        /// <summary>
        /// Every committed state written whole, by what it says it is rather than by what
        /// it is called - which is the point of a header.
        /// </summary>
        private static IEnumerable<string> WholeStates()
        {
            foreach (string path in Directory.EnumerateFiles(ScenarioRoot, "*.json").OrderBy(
                name => name, System.StringComparer.Ordinal))
            {
                string text = File.ReadAllText(path);
                JsonElement root;
                try
                {
                    using JsonDocument document = JsonDocument.Parse(text);
                    root = document.RootElement.Clone();
                }
                catch (JsonException)
                {
                    continue;
                }

                if (root.ValueKind == JsonValueKind.Object
                    && root.TryGetProperty(FormatStamp.FormatPropertyName, out JsonElement named)
                    && named.ValueKind == JsonValueKind.String
                    && named.GetString() == GlobalStateJson.FormatName)
                {
                    yield return path;
                }
            }
        }

        [Fact]
        public void EveryCommittedStateReadsAndWritesBackAsTheBytesItCameFrom()
        {
            string[] states = WholeStates().ToArray();
            Assert.True(
                states.Length >= AtLeast,
                $"found {states.Length} whole state fixtures, expected at least {AtLeast}");

            foreach (string path in states)
            {
                string name = Path.GetFileName(path);
                GlobalStateLoadResult loaded = GlobalStateJson.Deserialize(
                    File.ReadAllBytes(path), path);

                Assert.Equal(GlobalStateLoadOutcome.Loaded, loaded.Outcome);
                Assert.Equal(0, loaded.SkippedRowCount);

                // THE TRAILING NEWLINE IS THE REPOSITORY'S, not the writer's: every
                // committed text file ends in one and nothing this writes does.
                string expected = File.ReadAllText(path).TrimEnd('\n');
                string written = Encoding.UTF8.GetString(
                    GlobalStateJson.SerializeToUtf8Bytes(loaded.RequireState()));

                Assert.True(
                    expected == written,
                    $"{name} is not written back as the bytes it came from");
            }
        }
    }
}
