// SPDX-License-Identifier: MIT
//! The mod's own record of what a player has read, across every save.
//!
//! ## The shape
//!
//! ```json
//! {"_format":"global-state","_formatVersion":5,
//!  "conversations":{"WasOffered":{"3":"18"},"WasDisplayed":{"3":"17,19"}},
//!  "orbs":["APT ORB / aptbed"]}
//! ```
//!
//! Grouped by status, then by conversation, and each conversation's entry ids as one
//! [`super::runs`] string. A player reads a conversation by walking through it, so the ids
//! are clustered rather than scattered and a run costs a fraction of a list: measured on the
//! fixture that records every entry in the game, 423 KB of arrays against 22.5 KB of runs.
//!
//! `Untouched` is NEVER WRITTEN. An absent conversation or entry reads back as Untouched,
//! which is what makes a real file hold about a thousand entries rather than the 113,000
//! the game tracks.
//!
//! ## Reading is forgiving where writing is exact
//!
//! This file is the only copy of cross-save history and cannot be regenerated by replaying
//! the game. So a row that will not read is SKIPPED AND COUNTED rather than taken as a
//! reason to refuse the file: one malformed run must not cost a playthrough. What is
//! refused outright is a document that is not this format or not this version - a file full
//! of real history that this build would misread, which a caller must not overwrite.
//!
//! ## What comes out is byte for byte what a state means
//!
//! Statuses in the game's own order, conversations by id, entries ascending, orbs sorted,
//! and no indentation - so two equal states produce identical files and a state that did
//! not change produces no diff.
//!
//! ## THE ONE FORMAT HERE THE GAME LINKS RATHER THAN SPAWNS
//!
//! Every other format in [`super`] is reached from C# by running the engine host, which
//! suits a tool: a tool that cannot start a process has failed at something it can report.
//! This one is read and written from inside a running game, whose mod promises that an
//! engine failing to start costs a capability rather than a playthrough - the look-ahead is
//! a setting a player can switch off, and switching it off never stops the tracking. So the
//! game reaches THIS code, not a copy of it, through a small library built over this crate:
//! `crates/gct-state-ffi`, and `GlobalStateNative` on the other side.
//!
//! There is no second implementation to drift from. What the mod holds is the marshalling.

use std::collections::{BTreeMap, BTreeSet};

use super::header::{self, Expected, HeaderFault};
use super::runs;

/// What this document is called, and the version of it this build reads and writes.
pub const FORMAT: Expected = Expected {
    format: "global-state",
    version: 5,
};

/// Where the entries live.
pub const CONVERSATIONS_KEY: &str = "conversations";

/// Where the opened orbs live.
pub const ORBS_KEY: &str = "orbs";

/// How many complaints a read carries back. The count of skipped rows is not capped.
///
/// A malformed file can be malformed in thousands of identical ways, and a caller logging
/// all of them would bury everything else it had to say.
pub const MAX_WARNINGS: usize = 20;

/// What the game says about a dialogue entry.
///
/// ORDERED, and the order is the game's own numbering rather than an alphabet: it is what
/// decides which of two statuses for one entry wins, and what order the file lists them in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Status {
    /// Never offered or shown, which is what anything unrecorded is.
    Untouched,
    /// Offered as a response option and never shown.
    WasOffered,
    /// Shown to the player.
    WasDisplayed,
}

impl Status {
    /// The game's own string for it, which is what the file holds.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Untouched => "Untouched",
            Self::WasOffered => "WasOffered",
            Self::WasDisplayed => "WasDisplayed",
        }
    }

    /// The status a string names, or nothing where it names none.
    #[must_use]
    pub fn parse(text: &str) -> Option<Self> {
        match text {
            "Untouched" => Some(Self::Untouched),
            "WasOffered" => Some(Self::WasOffered),
            "WasDisplayed" => Some(Self::WasDisplayed),
            _ => None,
        }
    }
}

/// What a player has read, and which orbs they have opened.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct GlobalState {
    /// The status of every entry that has one, by conversation and then by entry.
    entries: BTreeMap<i32, BTreeMap<i32, Status>>,
    /// The conversation titles whose orb has been opened.
    orbs: BTreeSet<String>,
}

impl GlobalState {
    /// One with nothing in it, which is what a player who has read nothing has.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Records a status, KEEPING THE HIGHER of it and what is already there.
    ///
    /// Nothing can lower a status, which is what makes reading a damaged or hand-edited
    /// file safe: a row that says less than memory already knows is a row that changes
    /// nothing.
    ///
    /// Returns whether anything changed.
    pub fn merge(&mut self, conversation: i32, entry: i32, status: Status) -> bool {
        if status == Status::Untouched {
            return false;
        }

        let held = self.entries.entry(conversation).or_default();
        match held.get(&entry) {
            Some(was) if *was >= status => false,
            _ => {
                held.insert(entry, status);
                true
            }
        }
    }

    /// Records an opened orb by the conversation title the game keys it under.
    ///
    /// Returns whether it was new.
    pub fn merge_orb(&mut self, title: impl Into<String>) -> bool {
        self.orbs.insert(title.into())
    }

    /// What the state says about one entry, which is `Untouched` where it says nothing.
    #[must_use]
    pub fn status_of(&self, conversation: i32, entry: i32) -> Status {
        self.entries
            .get(&conversation)
            .and_then(|held| held.get(&entry))
            .copied()
            .unwrap_or(Status::Untouched)
    }

    /// The entries of a conversation at exactly this status, ascending.
    ///
    /// An entry has ONE status - the highest anything has recorded for it - so asking for
    /// one status is asking a complete question rather than a partial one.
    #[must_use]
    pub fn entries_at(&self, conversation: i32, status: Status) -> Vec<i32> {
        let Some(held) = self.entries.get(&conversation) else {
            return Vec::new();
        };

        held.iter()
            .filter(|(_, held)| **held == status)
            .map(|(entry, _)| *entry)
            .collect()
    }

    /// Every conversation the state says anything about, ascending.
    pub fn conversations(&self) -> impl Iterator<Item = i32> + '_ {
        self.entries.keys().copied()
    }

    /// Every opened orb, in the order the file lists them.
    pub fn orbs(&self) -> impl Iterator<Item = &str> {
        self.orbs.iter().map(String::as_str)
    }

    /// How many entries have a status at all.
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.values().map(BTreeMap::len).sum()
    }

    /// Whether it records nothing at all, orbs included.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty() && self.orbs.is_empty()
    }
}

/// Why a state could not be read at all.
///
/// Not the same thing as a row that would not read, which is skipped and counted - see
/// [`Loaded`]. Every one of these means the document is not a state this build can read,
/// and a caller holding one MUST NOT OVERWRITE THE FILE: it is somebody's history.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum StateFault {
    /// It is not JSON, or its root is not an object.
    #[error("{0} will not read: {1}")]
    Unreadable(String, String),
    /// Its header is not this format's, or not this version of it.
    #[error("{0}: {1}")]
    Header(String, #[source] HeaderFault),
    /// It is this format and leaves out something a state must say.
    #[error("{0} {1}")]
    Incomplete(String, &'static str),
}

/// What came of reading one.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Loaded {
    /// Everything that read.
    pub state: GlobalState,
    /// How many rows did not, which is counted in full however many there were.
    pub skipped: usize,
    /// What was wrong with the first [`MAX_WARNINGS`] of them.
    pub warnings: Vec<String>,
}

/// Reads one.
///
/// # Errors
///
/// Where the text is not JSON or not an object, where the header is not this format's, or
/// where it leaves out the conversations. A row that will not read is not an error: it is
/// counted in [`Loaded::skipped`] and described in [`Loaded::warnings`].
pub fn read(text: &str, context: &str) -> Result<Loaded, StateFault> {
    let document: serde_json::Value = serde_json::from_str(text)
        .map_err(|why| StateFault::Unreadable(context.to_string(), why.to_string()))?;

    read_document(&document, context)
}

/// Reads one that is already parsed.
///
/// [`read`] with the document in hand, which is how a caller that resolved a state written
/// as a change to another one - [`super::resolve`] - reaches this without writing the
/// result back out to text first.
///
/// # Errors
///
/// As [`read`], but for the parse.
pub fn read_document(document: &serde_json::Value, context: &str) -> Result<Loaded, StateFault> {
    // BEFORE THE HEADER, because a document that is not an object cannot have one. It is
    // DAMAGE rather than a document of another kind - a list or a bare string is not a file
    // anything here ever wrote - and the difference decides whether a caller may overwrite
    // it.
    if !document.is_object() {
        return Err(StateFault::Unreadable(
            context.to_string(),
            "it is not a JSON object".to_string(),
        ));
    }

    // BEFORE ANYTHING IS READ OFF IT, and this one matters more than most: the shapes in
    // this repository are all objects of objects, so a document of another kind read as a
    // state parses and yields whatever happened to line up - which here would be an empty
    // history that a caller might then write over the real one.
    FORMAT
        .check_document(document)
        .map_err(|why| StateFault::Header(context.to_string(), why))?;

    let conversations = document
        .get(CONVERSATIONS_KEY)
        .ok_or(StateFault::Incomplete(
            context.to_string(),
            "says nothing about any conversation",
        ))?
        .as_object()
        .ok_or(StateFault::Incomplete(
            context.to_string(),
            "has conversations that are not an object",
        ))?;

    let mut loaded = Loaded {
        state: GlobalState::new(),
        skipped: 0,
        warnings: Vec::new(),
    };

    for (name, held) in conversations {
        read_status(name, held, &mut loaded);
    }

    read_orbs(document.get(ORBS_KEY), &mut loaded);
    Ok(loaded)
}

/// One status block: a name this build knows, and a conversation map under it.
fn read_status(name: &str, held: &serde_json::Value, loaded: &mut Loaded) {
    let Some(held) = held.as_object() else {
        loaded.skip(1, format!("status '{name}' is not an object"));
        return;
    };

    // ONE COMPLAINT FOR THE WHOLE BLOCK where the status itself is unknown, rather than one
    // per conversation under it. There are only ever a handful of blocks, and spending the
    // budget on repetitions of one fact would push out every other complaint in the file.
    let Some(status) = Status::parse(name) else {
        let rows = held.values().map(rows_in).sum();
        loaded.skip(rows, format!("'{name}' is not a status this build knows"));
        return;
    };

    for (id, entries) in held {
        read_conversation(id, entries, status, loaded);
    }
}

/// One conversation's entries, which are a single run string.
fn read_conversation(id: &str, entries: &serde_json::Value, status: Status, loaded: &mut Loaded) {
    let Ok(conversation) = id.parse::<i32>() else {
        loaded.skip(
            rows_in(entries),
            format!(
                "conversation key '{id}' in '{}' is not a number",
                status.as_str()
            ),
        );
        return;
    };

    // A RUN STRING, because that is what the version at the top of the file says this holds.
    // Accepting a list here as well would quietly read a shape the version denies.
    let Some(text) = entries.as_str() else {
        loaded.skip(
            1,
            format!(
                "conversation {conversation} in '{}' is not a run of entry ids",
                status.as_str()
            ),
        );
        return;
    };

    let context = format!("conversation {conversation} in '{}'", status.as_str());
    match runs::unpack(text, &context) {
        // ONE SKIPPED ROW FOR A MALFORMED RUN, not one per id it might have held: nothing
        // in it can be trusted to mean what it says, so counting its entries would be
        // inventing a number.
        Err(why) => loaded.skip(1, why.to_string()),
        Ok(ids) => {
            for id in ids {
                match i32::try_from(id) {
                    Ok(entry) => {
                        loaded.state.merge(conversation, entry, status);
                    }
                    Err(_) => loaded.skip(1, format!("entry id {id} in {context} is out of range")),
                }
            }
        }
    }
}

/// The orb list, which an older file does not have and a damaged one may have wrongly.
fn read_orbs(orbs: Option<&serde_json::Value>, loaded: &mut Loaded) {
    let Some(orbs) = orbs else {
        return;
    };

    let Some(orbs) = orbs.as_array() else {
        loaded.skip(1, format!("'{ORBS_KEY}' is not a list"));
        return;
    };

    for orb in orbs {
        match orb.as_str() {
            Some(title) if !title.is_empty() => {
                loaded.state.merge_orb(title);
            }
            Some(_) => loaded.skip(1, "an orb has no conversation title".to_string()),
            None => loaded.skip(1, "an orb is not a conversation title".to_string()),
        }
    }
}

impl Loaded {
    /// Records rows that did not read, keeping the first few complaints.
    fn skip(&mut self, rows: usize, why: String) {
        self.skipped += rows;
        if self.warnings.len() < MAX_WARNINGS {
            self.warnings.push(why);
        }
    }
}

/// How many rows a value would have held, for the skipped count.
///
/// Anything that is not a readable run is ONE unusable row rather than none, so a file that
/// skipped something cannot report that it skipped nothing.
fn rows_in(entries: &serde_json::Value) -> usize {
    let Some(text) = entries.as_str() else {
        return 1;
    };

    runs::unpack(text, "")
        .map(|ids| ids.len().max(1))
        .unwrap_or(1)
}

/// Writes one, as the bytes the mod stores.
///
/// Written out by hand rather than through a serializer because two things about the
/// document are decided here and not by a value: the ORDER - statuses by the game's
/// numbering, then conversations by id - and the run encoding of each conversation's
/// entries, which is a string where the data is a set.
#[must_use]
pub fn write(state: &GlobalState) -> String {
    let mut text = String::new();
    text.push('{');
    text.push_str(&format!(
        "{}:{},{}:{},",
        quoted(header::FORMAT_KEY),
        quoted(FORMAT.format),
        quoted(header::VERSION_KEY),
        FORMAT.version,
    ));

    text.push_str(&format!("{}:{{", quoted(CONVERSATIONS_KEY)));
    let mut first = true;
    for (status, conversations) in by_status(state) {
        if !first {
            text.push(',');
        }
        first = false;

        text.push_str(&format!("{}:{{", quoted(status.as_str())));
        let mut leading = true;
        for (conversation, entries) in conversations {
            if !leading {
                text.push(',');
            }
            leading = false;

            let packed = runs::pack(&entries.iter().map(|id| i64::from(*id)).collect::<Vec<_>>());
            text.push_str(&format!(
                "{}:{}",
                quoted(&conversation.to_string()),
                quoted(&packed)
            ));
        }
        text.push('}');
    }
    text.push_str("},");

    // ALWAYS WRITTEN, even when empty, so "no orbs" and "orbs not recorded" cannot look
    // like the same file.
    text.push_str(&format!("{}:[", quoted(ORBS_KEY)));
    for (at, title) in state.orbs().enumerate() {
        if at > 0 {
            text.push(',');
        }
        text.push_str(&quoted(title));
    }
    text.push_str("]}");

    text
}

/// The entries by status and then by conversation, which is the order the file lists them.
fn by_status(state: &GlobalState) -> BTreeMap<Status, BTreeMap<i32, Vec<i32>>> {
    let mut by_status: BTreeMap<Status, BTreeMap<i32, Vec<i32>>> = BTreeMap::new();
    for (conversation, held) in &state.entries {
        for (entry, status) in held {
            by_status
                .entry(*status)
                .or_default()
                .entry(*conversation)
                .or_default()
                .push(*entry);
        }
    }

    by_status
}

/// One string as JSON, escaped the way a JSON writer would escape it.
fn quoted(text: &str) -> String {
    serde_json::Value::String(text.to_string()).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    const HEADER: &str = r#""_format": "global-state", "_formatVersion": 5"#;

    /// A document with the given conversations block and no orbs.
    fn document(conversations: &str) -> String {
        format!(r#"{{{HEADER}, "conversations": {conversations}, "orbs": []}}"#)
    }

    fn loaded(conversations: &str) -> Loaded {
        read(&document(conversations), "a state").expect("it reads")
    }

    #[test]
    fn a_state_holds_the_entries_its_runs_name() {
        let read = loaded(r#"{"WasDisplayed": {"9": "3,5,7-9"}}"#);

        assert_eq!(read.skipped, 0);
        assert_eq!(
            read.state.entries_at(9, Status::WasDisplayed),
            vec![3, 5, 7, 8, 9]
        );
        assert_eq!(read.state.status_of(9, 8), Status::WasDisplayed);
        // An entry nothing recorded is Untouched, which is what makes the file small.
        assert_eq!(read.state.status_of(9, 4), Status::Untouched);
        assert_eq!(read.state.status_of(11, 3), Status::Untouched);
    }

    /// An entry has one status, and it is the higher of whatever the file says twice.
    #[test]
    fn nothing_in_a_file_can_lower_a_status() {
        let read = loaded(r#"{"WasDisplayed": {"9": "3"}, "WasOffered": {"9": "3,4"}}"#);

        assert_eq!(read.state.status_of(9, 3), Status::WasDisplayed);
        assert_eq!(read.state.status_of(9, 4), Status::WasOffered);
    }

    #[test]
    fn the_orbs_are_the_titles_the_file_lists() {
        let read = read(
            &format!(r#"{{{HEADER}, "conversations": {{}}, "orbs": ["b", "a"]}}"#),
            "a state",
        )
        .expect("it reads");

        assert_eq!(read.state.orbs().collect::<Vec<_>>(), vec!["a", "b"]);
    }

    /// A document of another kind is REFUSED rather than read as an empty history, which a
    /// caller might then write over the real one.
    #[test]
    fn a_document_that_is_not_a_state_is_refused() {
        let why = read(
            r#"{"_format": "json-diff", "_formatVersion": 1, "conversations": {}}"#,
            "a diff",
        )
        .expect_err("it is refused");

        assert!(matches!(why, StateFault::Header(_, _)), "{why}");
    }

    #[test]
    fn a_state_of_another_version_is_refused() {
        let why = read(
            r#"{"_format": "global-state", "_formatVersion": 4, "conversations": {}}"#,
            "an older state",
        )
        .expect_err("it is refused");

        assert!(matches!(why, StateFault::Header(_, _)), "{why}");
    }

    #[test]
    fn a_state_that_says_nothing_about_conversations_is_refused() {
        let why =
            read(&format!(r#"{{{HEADER}, "orbs": []}}"#), "a state").expect_err("it is refused");

        assert!(matches!(why, StateFault::Incomplete(_, _)), "{why}");
    }

    #[test]
    fn text_that_is_not_json_is_refused() {
        let why = read("{", "a state").expect_err("it is refused");

        assert!(matches!(why, StateFault::Unreadable(_, _)), "{why}");
    }

    /// One malformed row costs that row, not the file: this is somebody's whole history.
    #[test]
    fn a_row_that_will_not_read_is_skipped_and_counted() {
        let read = loaded(r#"{"WasDisplayed": {"9": "3,x,5", "11": "7"}}"#);

        assert_eq!(read.skipped, 1);
        assert_eq!(read.warnings.len(), 1);
        assert!(read.state.entries_at(9, Status::WasDisplayed).is_empty());
        // And the rest of the file still reads.
        assert_eq!(read.state.entries_at(11, Status::WasDisplayed), vec![7]);
    }

    /// A status this build has no case for costs one complaint, not one per conversation.
    #[test]
    fn an_unknown_status_costs_one_complaint_and_the_rows_beneath_it() {
        let read =
            loaded(r#"{"WasSideways": {"9": "3,5", "11": "7"}, "WasDisplayed": {"2": "1"}}"#);

        assert_eq!(read.skipped, 3);
        assert_eq!(read.warnings.len(), 1);
        assert_eq!(read.state.entries_at(2, Status::WasDisplayed), vec![1]);
    }

    #[test]
    fn a_conversation_key_that_is_not_a_number_is_skipped() {
        let read = loaded(r#"{"WasDisplayed": {"nine": "3,5"}}"#);

        assert_eq!(read.skipped, 2);
        assert!(read.state.is_empty());
    }

    /// The shape is decided by the version at the top, so a list where a run belongs is a
    /// damaged current file rather than an older one, and is skipped as such.
    #[test]
    fn entries_written_as_a_list_are_skipped() {
        let read = loaded(r#"{"WasDisplayed": {"9": [3, 5]}}"#);

        assert_eq!(read.skipped, 1);
        assert!(read.state.is_empty());
    }

    #[test]
    fn an_orb_that_is_not_a_title_is_skipped() {
        let read = read(
            &format!(r#"{{{HEADER}, "conversations": {{}}, "orbs": ["a", 7, ""]}}"#),
            "a state",
        )
        .expect("it reads");

        assert_eq!(read.skipped, 2);
        assert_eq!(read.state.orbs().collect::<Vec<_>>(), vec!["a"]);
    }

    /// Statuses in the game's own order, conversations by id, entries as one run.
    #[test]
    fn what_is_written_is_ordered_and_run_encoded() {
        let mut state = GlobalState::new();
        state.merge(11, 4, Status::WasDisplayed);
        state.merge(9, 8, Status::WasDisplayed);
        state.merge(9, 7, Status::WasDisplayed);
        state.merge(9, 3, Status::WasOffered);
        state.merge_orb("an orb");

        assert_eq!(
            write(&state),
            r#"{"_format":"global-state","_formatVersion":5,"conversations":{"WasOffered":{"9":"3"},"WasDisplayed":{"9":"7-8","11":"4"}},"orbs":["an orb"]}"#,
        );
    }

    /// An empty state still says so, rather than leaving the reader to guess.
    #[test]
    fn an_empty_state_writes_both_of_its_halves() {
        assert_eq!(
            write(&GlobalState::new()),
            r#"{"_format":"global-state","_formatVersion":5,"conversations":{},"orbs":[]}"#,
        );
    }

    #[test]
    fn what_is_written_reads_back_as_the_state_it_came_from() {
        let mut state = GlobalState::new();
        state.merge(9, 3, Status::WasOffered);
        state.merge(9, 4, Status::WasDisplayed);
        state.merge_orb("APT ORB / aptbed");

        let back = read(&write(&state), "what was written").expect("it reads");

        assert_eq!(back.state, state);
        assert_eq!(back.skipped, 0);
    }
}
