// SPDX-License-Identifier: MIT
//! The mod's state file, as a C interface the game's own process can call.
//!
//! ## Why this exists at all
//!
//! So that the state format has ONE implementation. Every other format C# needs it reaches
//! by running `gct-engine-host`, and that is fine for a tool: a tool that cannot start a
//! process has failed at something it can say out loud. The state file is not like that. It
//! is the only copy of cross-save history, it cannot be regenerated by replaying the game,
//! and it is read and written from inside a running game whose mod promises that an engine
//! failing to start costs a capability rather than a playthrough. A library that is simply
//! linked has no absent process to answer for.
//!
//! ## What crosses, and what does not
//!
//! A state is entries and orbs. Reading hands back a flat array of `(conversation, entry,
//! status)` and the orb titles; writing takes the same and hands back the bytes. The worst
//! case this repository holds is 113,000 entries - about 1.3 MB of array, once per load and
//! once per save - which does not justify a chattier interface, and a flat array has
//! nothing to get wrong.
//!
//! WHAT DOES NOT CROSS is durability. The temp file, the flush, the rotation onto the
//! backup and the single writer thread stay in C#, where the writing happens. Those are
//! storage policy, not format, and the contract they keep is why the file survives a crash.
//!
//! ## The rules this interface plays by
//!
//! EVERY POINTER THIS HANDS OUT IS OWNED BY THE HANDLE IT CAME FROM and is valid until that
//! handle is freed. Nothing is null-terminated: a conversation title is arbitrary text, so
//! every string is a pointer and a length.
//!
//! NOTHING UNWINDS ACROSS THE BOUNDARY. A panic crossing into C# is undefined behaviour, so
//! every entry point catches one and answers the way it answers a bad document.
//!
//! A NULL HANDLE IS A VALID ARGUMENT everywhere, and means "nothing": a caller that failed
//! to get one does not have to branch before freeing or asking.

use std::panic::{AssertUnwindSafe, catch_unwind};

use gct_formats::global_state::{self, GlobalState, Loaded, StateFault, Status};
use gct_formats::header::HeaderFault;
use gct_formats::save_statuses;

/// The document read, and everything that would not.
pub const OUTCOME_LOADED: i32 = 0;

/// It is not JSON, is not an object, or leaves out what a state must say.
///
/// The caller may overwrite the file: nothing in it could be read.
pub const OUTCOME_CORRUPT: i32 = 1;

/// It is a document of another kind, or a newer version of this one.
///
/// The caller MUST NOT overwrite the file. It is not damaged, and what it holds is real
/// history that a build which cannot read it must leave alone.
pub const OUTCOME_UNSUPPORTED: i32 = 2;

/// It is this format from before the version this build reads: it names no format, carries
/// no version, or carries an older one.
///
/// The caller MUST NOT overwrite the file, for the same reason as
/// [`OUTCOME_UNSUPPORTED`]. The difference is the remedy - this one converts - and so the
/// words a player is shown.
pub const OUTCOME_OUTDATED: i32 = 3;

/// One entry's status, as the game numbers it.
const STATUSES: [Status; 3] = [Status::Untouched, Status::WasOffered, Status::WasDisplayed];

/// One entry of a state, as it crosses.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Entry {
    pub conversation: i32,
    pub entry: i32,
    /// 0 untouched, 1 offered, 2 displayed - [`STATUSES`] by index.
    pub status: i32,
}

/// What a read produced, kept alive for the caller to copy out of.
pub struct Read {
    outcome: i32,
    /// Why it was refused, where it was. Empty otherwise.
    message: String,
    skipped: usize,
    warnings: Vec<String>,
    entries: Vec<Entry>,
    orbs: Vec<String>,
}

/// Bytes a write produced, kept alive for the caller to copy out of.
pub struct Bytes(Vec<u8>);

/// Reads a state file.
///
/// Always answers with a handle, whatever went wrong - the outcome and the message are on
/// it. Only an allocation failure gives null.
///
/// # Safety
///
/// `json` must point to `len` readable bytes, or be null with `len` zero.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_read(json: *const u8, len: usize) -> *mut Read {
    let read = catch_unwind(AssertUnwindSafe(|| {
        let bytes = if json.is_null() || len == 0 {
            &[][..]
        } else {
            // SAFETY: the caller's contract, restated above.
            unsafe { std::slice::from_raw_parts(json, len) }
        };

        match std::str::from_utf8(bytes) {
            // A FILE THAT IS NOT UTF-8 IS A TORN WRITE, not a state in another encoding:
            // this format is written UTF-8 without a byte order mark and nothing else ever
            // wrote it.
            Err(why) => refused(OUTCOME_CORRUPT, format!("it is not UTF-8 text: {why}")),
            Ok(text) => match global_state::read(text, "the state file") {
                Ok(loaded) => accepted(loaded),
                Err(fault) => refused(outcome_of(&fault), fault.to_string()),
            },
        }
    }));

    match read {
        Ok(read) => Box::into_raw(Box::new(read)),
        Err(_) => Box::into_raw(Box::new(refused(
            OUTCOME_CORRUPT,
            "reading it ended in a panic".to_string(),
        ))),
    }
}

/// Reads the dialogue statuses out of a save's Lua blob.
///
/// ## Why this is here, beside the state file
///
/// Because the mod reads BOTH from inside the running game, on the same save load. The
/// state file is what it has recorded across playthroughs and the save is what this one has
/// shown; it refills the second from the first. Reading the save was the last format the
/// plugin still parsed for itself, in C#, which made the save's Lua blob a thing this
/// repository defined twice.
///
/// WHAT COMES BACK IS THE SAME HANDLE a state read gives, because what it holds is the same
/// thing: a status per entry. Every accessor works on it - the outcome, the message, the
/// count and the entries - and it is freed the same way. There are no orbs and no warnings
/// in one, and asking for them answers nothing rather than failing.
///
/// A BLOB THAT WILL NOT READ IS `OUTCOME_CORRUPT` and never `OUTCOME_UNSUPPORTED`: the
/// distinction the state file draws is about a document whose history must not be
/// overwritten, and a save is the game's own file that this never writes.
///
/// # Safety
///
/// `blob` must point to `len` readable bytes, or be null with `len` zero.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_read_save(blob: *const u8, len: usize) -> *mut Read {
    let read = catch_unwind(AssertUnwindSafe(|| {
        let bytes = if blob.is_null() || len == 0 {
            &[][..]
        } else {
            // SAFETY: the caller's contract, restated above.
            unsafe { std::slice::from_raw_parts(blob, len) }
        };

        match save_statuses::in_blob(bytes) {
            Ok(state) => from_state(&state),
            Err(fault) => refused(OUTCOME_CORRUPT, fault.to_string()),
        }
    }));

    match read {
        Ok(read) => Box::into_raw(Box::new(read)),
        Err(_) => Box::into_raw(Box::new(refused(
            OUTCOME_CORRUPT,
            "reading the save ended in a panic".to_string(),
        ))),
    }
}

/// Which refusal a fault is.
///
/// The distinction is what the caller does next: a document this build cannot read is full
/// of somebody's history and must be left alone, where one that will not parse at all holds
/// nothing to lose. Among the ones left alone, an older document is brought forward by the
/// converter, and a newer one or another kind of document is not.
///
/// A DOCUMENT THAT NAMES NO FORMAT IS AN OLDER ONE. Naming itself is what every current
/// format added, so silence is what a file from before that looks like.
fn outcome_of(fault: &StateFault) -> i32 {
    match fault {
        StateFault::Header(_, HeaderFault::Unnamed { .. } | HeaderFault::Unstamped { .. }) => {
            OUTCOME_OUTDATED
        }
        StateFault::Header(_, HeaderFault::Version { found, current, .. }) if found < current => {
            OUTCOME_OUTDATED
        }
        StateFault::Header(_, _) => OUTCOME_UNSUPPORTED,
        StateFault::Unreadable(_, _) | StateFault::Incomplete(_, _) => OUTCOME_CORRUPT,
    }
}

fn refused(outcome: i32, message: String) -> Read {
    Read {
        outcome,
        message,
        skipped: 0,
        warnings: Vec::new(),
        entries: Vec::new(),
        orbs: Vec::new(),
    }
}

fn accepted(loaded: Loaded) -> Read {
    Read {
        skipped: loaded.skipped,
        warnings: loaded.warnings,
        orbs: loaded.state.orbs().map(str::to_string).collect(),
        ..from_state(&loaded.state)
    }
}

/// A state as the flat array that crosses, with nothing else said about it.
///
/// Shared by the two reads, because a save and the state file hand back the same thing.
fn from_state(state: &GlobalState) -> Read {
    let mut entries = Vec::with_capacity(state.len());
    for conversation in state.conversations() {
        for (at, status) in STATUSES.iter().enumerate() {
            for entry in state.entries_at(conversation, *status) {
                entries.push(Entry {
                    conversation,
                    entry,
                    status: i32::try_from(at).expect("three statuses fit in an i32"),
                });
            }
        }
    }

    Read {
        outcome: OUTCOME_LOADED,
        message: String::new(),
        skipped: 0,
        warnings: Vec::new(),
        entries,
        orbs: Vec::new(),
    }
}

/// What came of a read: one of the three outcomes.
///
/// # Safety
///
/// `read` must be a handle from [`gct_state_read`] that has not been freed, or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_outcome(read: *const Read) -> i32 {
    // SAFETY: the caller's contract.
    match unsafe { read.as_ref() } {
        Some(read) => read.outcome,
        None => OUTCOME_CORRUPT,
    }
}

/// Why it was refused, as UTF-8 bytes. Empty where it was not.
///
/// # Safety
///
/// As [`gct_state_outcome`]; `len` must be writable.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_message(read: *const Read, len: *mut usize) -> *const u8 {
    // SAFETY: the caller's contract.
    unsafe { text_of(read.as_ref().map(|read| read.message.as_str()), len) }
}

/// How many rows would not read. Counted in full, however many there were.
///
/// # Safety
///
/// As [`gct_state_outcome`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_skipped(read: *const Read) -> usize {
    // SAFETY: the caller's contract.
    unsafe { read.as_ref() }.map_or(0, |read| read.skipped)
}

/// How many of those are described.
///
/// # Safety
///
/// As [`gct_state_outcome`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_warning_count(read: *const Read) -> usize {
    // SAFETY: the caller's contract.
    unsafe { read.as_ref() }.map_or(0, |read| read.warnings.len())
}

/// One description, as UTF-8 bytes. Empty where there is no such one.
///
/// # Safety
///
/// As [`gct_state_message`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_warning(
    read: *const Read,
    at: usize,
    len: *mut usize,
) -> *const u8 {
    // SAFETY: the caller's contract.
    let warning = unsafe { read.as_ref() }.and_then(|read| read.warnings.get(at));
    // SAFETY: as above.
    unsafe { text_of(warning.map(String::as_str), len) }
}

/// How many entries the state holds.
///
/// # Safety
///
/// As [`gct_state_outcome`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_entry_count(read: *const Read) -> usize {
    // SAFETY: the caller's contract.
    unsafe { read.as_ref() }.map_or(0, |read| read.entries.len())
}

/// Copies up to `capacity` entries out, and says how many it copied.
///
/// # Safety
///
/// `out` must point to room for `capacity` [`Entry`] values, and `read` must be a live
/// handle or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_entries(
    read: *const Read,
    out: *mut Entry,
    capacity: usize,
) -> usize {
    // SAFETY: the caller's contract.
    let Some(read) = (unsafe { read.as_ref() }) else {
        return 0;
    };
    if out.is_null() {
        return 0;
    }

    let taken = read.entries.len().min(capacity);
    // SAFETY: `out` has room for `capacity`, and `taken` is no larger.
    unsafe { std::ptr::copy_nonoverlapping(read.entries.as_ptr(), out, taken) };
    taken
}

/// How many orbs the state holds.
///
/// # Safety
///
/// As [`gct_state_outcome`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_orb_count(read: *const Read) -> usize {
    // SAFETY: the caller's contract.
    unsafe { read.as_ref() }.map_or(0, |read| read.orbs.len())
}

/// One orb's conversation title, as UTF-8 bytes.
///
/// # Safety
///
/// As [`gct_state_message`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_orb(read: *const Read, at: usize, len: *mut usize) -> *const u8 {
    // SAFETY: the caller's contract.
    let orb = unsafe { read.as_ref() }.and_then(|read| read.orbs.get(at));
    // SAFETY: as above.
    unsafe { text_of(orb.map(String::as_str), len) }
}

/// Releases what a read produced. Null is nothing to release.
///
/// # Safety
///
/// `read` must be a handle from [`gct_state_read`] that has not already been freed.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_read_free(read: *mut Read) {
    if !read.is_null() {
        // SAFETY: the caller's contract.
        drop(unsafe { Box::from_raw(read) });
    }
}

/// Writes a state out.
///
/// The orb titles arrive as one UTF-8 buffer and a list of their lengths, rather than as an
/// array of pointers, because that is one allocation on the caller's side instead of one per
/// title.
///
/// Returns null only where an allocation failed or a length list does not add up to the
/// buffer it describes.
///
/// # Safety
///
/// `entries` must point to `count` [`Entry`] values; `orb_text` to `orb_text_len` bytes; and
/// `orb_lengths` to `orb_count` lengths that sum to `orb_text_len`. Any of them may be null
/// with its count zero.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_write(
    entries: *const Entry,
    count: usize,
    orb_text: *const u8,
    orb_text_len: usize,
    orb_lengths: *const usize,
    orb_count: usize,
) -> *mut Bytes {
    let written = catch_unwind(AssertUnwindSafe(|| {
        let mut state = GlobalState::new();

        // SAFETY: the caller's contract.
        for held in unsafe { slice_of(entries, count) } {
            let Some(status) = STATUSES.get(usize::try_from(held.status).ok()?) else {
                return None;
            };
            state.merge(held.conversation, held.entry, *status);
        }

        // SAFETY: as above.
        let text = unsafe { slice_of(orb_text, orb_text_len) };
        // SAFETY: as above.
        let lengths = unsafe { slice_of(orb_lengths, orb_count) };
        let mut at: usize = 0;
        for length in lengths {
            let end = at.checked_add(*length)?;
            // A LIST OF LENGTHS THAT DOES NOT ADD UP is a caller that has miscounted, and
            // writing whatever happens to be in range would produce a state file holding
            // half a title. Refused instead.
            let title = std::str::from_utf8(text.get(at..end)?).ok()?;
            state.merge_orb(title);
            at = end;
        }
        if at != text.len() {
            return None;
        }

        Some(Bytes(global_state::write(&state).into_bytes()))
    }));

    match written {
        Ok(Some(bytes)) => Box::into_raw(Box::new(bytes)),
        Ok(None) | Err(_) => std::ptr::null_mut(),
    }
}

/// What a write produced, as UTF-8 bytes.
///
/// # Safety
///
/// `bytes` must be a handle from [`gct_state_write`] that has not been freed, or null, and
/// `len` must be writable.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_bytes(bytes: *const Bytes, len: *mut usize) -> *const u8 {
    // SAFETY: the caller's contract.
    let held = unsafe { bytes.as_ref() };
    let held = held.map_or(&[][..], |bytes| bytes.0.as_slice());
    if !len.is_null() {
        // SAFETY: the caller's contract.
        unsafe { *len = held.len() };
    }

    held.as_ptr()
}

/// Releases what a write produced. Null is nothing to release.
///
/// # Safety
///
/// `bytes` must be a handle from [`gct_state_write`] that has not already been freed.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_bytes_free(bytes: *mut Bytes) {
    if !bytes.is_null() {
        // SAFETY: the caller's contract.
        drop(unsafe { Box::from_raw(bytes) });
    }
}

/// What this format calls itself, as UTF-8 bytes.
///
/// Asked rather than restated, so the name cannot be spelled two ways.
///
/// # Safety
///
/// `len` must be writable or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gct_state_format_name(len: *mut usize) -> *const u8 {
    // SAFETY: the caller's contract.
    unsafe { text_of(Some(global_state::FORMAT.format), len) }
}

/// The version of it this library reads and writes.
#[unsafe(no_mangle)]
pub extern "C" fn gct_state_format_version() -> u32 {
    global_state::FORMAT.version
}

/// How many skipped rows a read describes before it stops describing them.
#[unsafe(no_mangle)]
pub extern "C" fn gct_state_max_warnings() -> usize {
    global_state::MAX_WARNINGS
}

/// A string as a pointer and a length, with the length written where the caller asked.
///
/// # Safety
///
/// `len` must be writable or null.
unsafe fn text_of(text: Option<&str>, len: *mut usize) -> *const u8 {
    let text = text.unwrap_or_default();
    if !len.is_null() {
        // SAFETY: the caller's contract.
        unsafe { *len = text.len() };
    }

    text.as_ptr()
}

/// A slice over what a caller passed, which is empty where it passed nothing.
///
/// # Safety
///
/// `first` must point to `count` readable values, or be null with `count` zero.
unsafe fn slice_of<'a, T>(first: *const T, count: usize) -> &'a [T] {
    if first.is_null() || count == 0 {
        return &[];
    }

    // SAFETY: the caller's contract.
    unsafe { std::slice::from_raw_parts(first, count) }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Reads a document the way C# will, and hands back the handle to ask about.
    fn read_of(text: &str) -> *mut Read {
        unsafe { gct_state_read(text.as_ptr(), text.len()) }
    }

    /// One string the interface handed out, copied back into Rust to be compared.
    fn text_at(first: *const u8, len: usize) -> String {
        if first.is_null() || len == 0 {
            return String::new();
        }

        String::from_utf8(unsafe { std::slice::from_raw_parts(first, len) }.to_vec())
            .expect("everything this hands out is UTF-8")
    }

    fn entries_of(read: *mut Read) -> Vec<Entry> {
        let count = unsafe { gct_state_entry_count(read) };
        let mut held = vec![
            Entry {
                conversation: 0,
                entry: 0,
                status: 0
            };
            count
        ];
        let taken = unsafe { gct_state_entries(read, held.as_mut_ptr(), count) };
        assert_eq!(taken, count);
        held
    }

    fn orbs_of(read: *mut Read) -> Vec<String> {
        let count = unsafe { gct_state_orb_count(read) };
        (0..count)
            .map(|at| {
                let mut len = 0;
                let first = unsafe { gct_state_orb(read, at, &raw mut len) };
                text_at(first, len)
            })
            .collect()
    }

    /// Writes one the way C# will: the entries, and the titles as one buffer and its lengths.
    fn write_of(entries: &[Entry], orbs: &[&str]) -> Option<String> {
        let text: String = orbs.concat();
        let lengths: Vec<usize> = orbs.iter().map(|orb| orb.len()).collect();
        let bytes = unsafe {
            gct_state_write(
                entries.as_ptr(),
                entries.len(),
                text.as_ptr(),
                text.len(),
                lengths.as_ptr(),
                lengths.len(),
            )
        };
        if bytes.is_null() {
            return None;
        }

        let mut len = 0;
        let first = unsafe { gct_state_bytes(bytes, &raw mut len) };
        let written = text_at(first, len);
        unsafe { gct_state_bytes_free(bytes) };
        Some(written)
    }

    const A_STATE: &str = concat!(
        r#"{"_format":"global-state","_formatVersion":5,"conversations":"#,
        r#"{"WasOffered":{"9":"3"},"WasDisplayed":{"9":"7-8","11":"4"}},"orbs":["an orb"]}"#,
    );

    #[test]
    fn a_state_crosses_as_its_entries_and_its_orbs() {
        let read = read_of(A_STATE);

        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_LOADED);
        assert_eq!(unsafe { gct_state_skipped(read) }, 0);
        let entries = entries_of(read);
        assert_eq!(entries.len(), 4);
        assert_eq!(
            entries
                .iter()
                .map(|held| (held.conversation, held.entry, held.status))
                .collect::<Vec<_>>(),
            vec![(9, 3, 1), (9, 7, 2), (9, 8, 2), (11, 4, 2)],
        );
        assert_eq!(orbs_of(read), vec!["an orb".to_string()]);

        unsafe { gct_state_read_free(read) };
    }

    /// And goes back out as the bytes it came in as, which is what one implementation means.
    #[test]
    fn what_crossed_writes_back_as_the_document_it_came_from() {
        let read = read_of(A_STATE);
        let entries = entries_of(read);
        let orbs = orbs_of(read);
        unsafe { gct_state_read_free(read) };

        let written = write_of(
            &entries,
            &orbs.iter().map(String::as_str).collect::<Vec<_>>(),
        );

        assert_eq!(written.as_deref(), Some(A_STATE));
    }

    /// A document of another kind must not be overwritten, and says so by its outcome.
    #[test]
    fn a_document_of_another_kind_is_unsupported_rather_than_corrupt() {
        let read = read_of(r#"{"_format":"json-diff","_formatVersion":1,"conversations":{}}"#);

        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_UNSUPPORTED);
        let mut len = 0;
        let message = text_at(unsafe { gct_state_message(read, &raw mut len) }, len);
        assert!(message.contains("json-diff"), "{message}");

        unsafe { gct_state_read_free(read) };
    }

    /// A state from before the version this reads is outdated, and names the converter.
    #[test]
    fn an_older_state_is_outdated_rather_than_unsupported() {
        for older in [
            r#"{"version":4,"conversations":{}}"#,
            r#"{"_format":"global-state","conversations":{}}"#,
            r#"{"_format":"global-state","_formatVersion":0,"conversations":{}}"#,
        ] {
            let read = read_of(older);

            assert_eq!(
                unsafe { gct_state_outcome(read) },
                OUTCOME_OUTDATED,
                "{older}"
            );
            let mut len = 0;
            let message = text_at(unsafe { gct_state_message(read, &raw mut len) }, len);
            assert!(
                message.contains(gct_formats::header::CONVERTER),
                "{older}: {message}"
            );

            unsafe { gct_state_read_free(read) };
        }
    }

    /// A state from a newer build is unsupported, which is not something to convert.
    #[test]
    fn a_newer_state_is_unsupported() {
        let read = read_of(r#"{"_format":"global-state","_formatVersion":99,"conversations":{}}"#);

        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_UNSUPPORTED);

        unsafe { gct_state_read_free(read) };
    }

    #[test]
    fn text_that_is_not_json_is_corrupt() {
        let read = read_of("{");

        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_CORRUPT);

        unsafe { gct_state_read_free(read) };
    }

    /// A torn write is not a state in another encoding, and reads as damage.
    #[test]
    fn bytes_that_are_not_utf8_are_corrupt() {
        let bytes = [0x7b, 0xff, 0xfe];
        let read = unsafe { gct_state_read(bytes.as_ptr(), bytes.len()) };

        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_CORRUPT);

        unsafe { gct_state_read_free(read) };
    }

    #[test]
    fn a_row_that_will_not_read_is_counted_and_described() {
        let read = read_of(concat!(
            r#"{"_format":"global-state","_formatVersion":5,"#,
            r#""conversations":{"WasDisplayed":{"9":"3,x"}},"orbs":[]}"#,
        ));

        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_LOADED);
        assert_eq!(unsafe { gct_state_skipped(read) }, 1);
        assert_eq!(unsafe { gct_state_warning_count(read) }, 1);
        let mut len = 0;
        let warning = text_at(unsafe { gct_state_warning(read, 0, &raw mut len) }, len);
        assert!(!warning.is_empty());

        unsafe { gct_state_read_free(read) };
    }

    /// Nothing at all is a valid argument everywhere, so a caller that failed to get a
    /// handle does not have to branch before asking or freeing.
    #[test]
    /// A save's blob crosses as the same entries a state file's does.
    #[test]
    fn a_saves_statuses_cross_as_the_entries_a_state_reads_as() {
        let blob = gct_formats::lua_blob::write(&save_holding(10, 5, "WasDisplayed"));

        let read = unsafe { gct_state_read_save(blob.as_ptr(), blob.len()) };

        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_LOADED);
        assert_eq!(
            entries_of(read),
            vec![Entry {
                conversation: 10,
                entry: 5,
                status: 2,
            }],
        );
        unsafe { gct_state_read_free(read) };
    }

    /// And it has no orbs and no skipped rows, which is asking rather than failing.
    #[test]
    fn a_save_has_nothing_to_say_about_orbs_or_skipped_rows() {
        let blob = gct_formats::lua_blob::write(&save_holding(1, 2, "WasOffered"));

        let read = unsafe { gct_state_read_save(blob.as_ptr(), blob.len()) };

        assert_eq!(orbs_of(read), Vec::<String>::new());
        assert_eq!(unsafe { gct_state_skipped(read) }, 0);
        assert_eq!(unsafe { gct_state_warning_count(read) }, 0);
        unsafe { gct_state_read_free(read) };
    }

    /// Bytes that are not a blob are corrupt, and never unsupported: a save is the game's
    /// own file and nothing here would overwrite it either way.
    #[test]
    fn bytes_that_are_not_a_blob_are_corrupt_and_say_why() {
        let bytes = b"not a blob at all";

        let read = unsafe { gct_state_read_save(bytes.as_ptr(), bytes.len()) };

        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_CORRUPT);
        let mut len = 0;
        let first = unsafe { gct_state_message(read, &raw mut len) };
        assert!(!text_at(first, len).is_empty(), "a refusal says why");
        unsafe { gct_state_read_free(read) };
    }

    #[test]
    fn no_bytes_at_all_is_a_refusal_rather_than_an_empty_save() {
        let read = unsafe { gct_state_read_save(std::ptr::null(), 0) };

        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_CORRUPT);
        unsafe { gct_state_read_free(read) };
    }

    /// The five tables a blob holds, with one status recorded in the conversations.
    fn save_holding(conversation: i32, entry: i32, status: &str) -> gct_formats::lua_blob::Blob {
        use gct_formats::lua_blob::{Blob, LuaTable, LuaValue, TABLE_NAMES};
        use gct_formats::save_statuses::{DIALOG_FIELD, SIM_STATUS_FIELD};

        let keyed = |entries: Vec<(LuaValue, LuaValue)>| LuaTable {
            list: Vec::new(),
            dict: entries,
        };
        let text = |what: &str| LuaValue::Text(what.to_string());

        let conversations = keyed(vec![(
            text(&conversation.to_string()),
            LuaValue::Table(keyed(vec![(
                text(DIALOG_FIELD),
                LuaValue::Table(keyed(vec![(
                    text(&entry.to_string()),
                    LuaValue::Table(keyed(vec![(text(SIM_STATUS_FIELD), text(status))])),
                )])),
            )])),
        )]);

        Blob {
            tables: TABLE_NAMES
                .iter()
                .map(|name| {
                    if *name == "Conversation" {
                        LuaValue::Table(conversations.clone())
                    } else {
                        LuaValue::Table(LuaTable::default())
                    }
                })
                .collect(),
            trailing: Vec::new(),
        }
    }

    #[test]
    fn a_null_handle_answers_rather_than_crashing() {
        let nothing: *mut Read = std::ptr::null_mut();

        assert_eq!(unsafe { gct_state_outcome(nothing) }, OUTCOME_CORRUPT);
        assert_eq!(unsafe { gct_state_entry_count(nothing) }, 0);
        assert_eq!(unsafe { gct_state_orb_count(nothing) }, 0);
        assert_eq!(unsafe { gct_state_skipped(nothing) }, 0);
        assert_eq!(unsafe { gct_state_warning_count(nothing) }, 0);
        unsafe { gct_state_read_free(nothing) };
        unsafe { gct_state_bytes_free(std::ptr::null_mut()) };
    }

    #[test]
    fn an_empty_state_crosses_both_ways() {
        let written = write_of(&[], &[]).expect("it writes");

        assert_eq!(
            written,
            r#"{"_format":"global-state","_formatVersion":5,"conversations":{},"orbs":[]}"#,
        );

        let read = read_of(&written);
        assert_eq!(unsafe { gct_state_outcome(read) }, OUTCOME_LOADED);
        assert_eq!(unsafe { gct_state_entry_count(read) }, 0);
        unsafe { gct_state_read_free(read) };
    }

    /// A caller that has miscounted its titles is refused, rather than writing half of one.
    #[test]
    fn orb_lengths_that_do_not_add_up_are_refused() {
        let text = "an orb";
        let lengths = [text.len() + 1];
        let bytes = unsafe {
            gct_state_write(
                std::ptr::null(),
                0,
                text.as_ptr(),
                text.len(),
                lengths.as_ptr(),
                lengths.len(),
            )
        };

        assert!(bytes.is_null());
    }

    #[test]
    fn what_the_library_says_about_itself_is_the_format_s_own_answer() {
        let mut len = 0;
        let name = text_at(unsafe { gct_state_format_name(&raw mut len) }, len);

        assert_eq!(name, global_state::FORMAT.format);
        assert_eq!(gct_state_format_version(), global_state::FORMAT.version);
        assert_eq!(gct_state_max_warnings(), global_state::MAX_WARNINGS);
    }
}
